//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_3x53by3v {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_3x53by3v() {
        }
        
        static object Create_ASP_linkbankaccount_aspx() {
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                return @__activator.GetService(typeof(ASP.linkbankaccount_aspx));
            }
            else {
                return new ASP.linkbankaccount_aspx();
            }
        }
        
        static object Create_ASP_sendmoney_aspx() {
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                return @__activator.GetService(typeof(ASP.sendmoney_aspx));
            }
            else {
                return new ASP.sendmoney_aspx();
            }
        }
        
        static object Create_ASP_default_aspx() {
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                return @__activator.GetService(typeof(ASP.default_aspx));
            }
            else {
                return new ASP.default_aspx();
            }
        }
        
        static object Create_ASP_fixeddeposit_aspx() {
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                return @__activator.GetService(typeof(ASP.fixeddeposit_aspx));
            }
            else {
                return new ASP.fixeddeposit_aspx();
            }
        }
        
        static object Create_ASP_site_mobile_master() {
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                return @__activator.GetService(typeof(ASP.site_mobile_master));
            }
            else {
                return new ASP.site_mobile_master();
            }
        }
        
        static object Create_ASP_about_aspx() {
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                return @__activator.GetService(typeof(ASP.about_aspx));
            }
            else {
                return new ASP.about_aspx();
            }
        }
        
        static object Create_ASP_billpayment_aspx() {
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                return @__activator.GetService(typeof(ASP.billpayment_aspx));
            }
            else {
                return new ASP.billpayment_aspx();
            }
        }
        
        static object Create_ASP_transactionhistory_aspx() {
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                return @__activator.GetService(typeof(ASP.transactionhistory_aspx));
            }
            else {
                return new ASP.transactionhistory_aspx();
            }
        }
        
        static object Create_ASP_managebeneficiaries_aspx() {
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                return @__activator.GetService(typeof(ASP.managebeneficiaries_aspx));
            }
            else {
                return new ASP.managebeneficiaries_aspx();
            }
        }
        
        static object Create_ASP_contact_aspx() {
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                return @__activator.GetService(typeof(ASP.contact_aspx));
            }
            else {
                return new ASP.contact_aspx();
            }
        }
    }
}
