#pragma checksum "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx" "{8829d00f-11b8-4213-878b-770e8597ac16}" "D859B9C33B3E91342D973BB98A4FFF117CBBD6F268B02784843E6235F9D6D553"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 335 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 13 "D:\Project\OnlineBankingTransactionSystem\web.config"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 335 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 335 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 335 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 335 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class adminlogin_aspx : global::OnlineBankingTransactionSystem.AdminLogin, System.Web.SessionState.IRequiresSessionState, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.adminlogin_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        
        #line 335 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
        protected global::System.Web.UI.WebControls.Label lblError;
        
        #line default
        #line hidden
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public adminlogin_aspx() {
            string[] dependencies;
            ((global::OnlineBankingTransactionSystem.AdminLogin)(this)).AppRelativeVirtualPath = "~/AdminLogin.aspx";
            if ((global::ASP.adminlogin_aspx.@__initialized == false)) {
                dependencies = new string[1];
                dependencies[0] = "~/AdminLogin.aspx";
                global::ASP.adminlogin_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.adminlogin_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(this.Context.ApplicationInstance));
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n    <!DOCTYPE html>\r\n    <html lang=\"en\">\r\n\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        138,
                        53,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.WebTools.BrowserLink.Runtime.WebForms.TraceHelpers, Microsoft.WebTools." +
                    "BrowserLink.Tracing, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f1" +
                    "1d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.adminlogin_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.adminlogin_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlMeta)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlMeta))));
            }
            else {
                
                #line 8 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
                
                #line default
                #line hidden
            }
            
            #line 8 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("charset", "UTF-8");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        222,
                        24,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control5() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlMeta)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlMeta))));
            }
            else {
                
                #line 9 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
                
                #line default
                #line hidden
            }
            
            #line 9 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl.Name = "viewport";
            
            #line default
            #line hidden
            
            #line 9 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl.Content = "width=device-width, initial-scale=1.0";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        256,
                        72,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control7() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("Admin Login — NeoBank");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        345,
                        21,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control6() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlTitle)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlTitle))));
            }
            else {
                
                #line 10 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
                
                #line default
                #line hidden
            }
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 10 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl1 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 10 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        338,
                        36,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control8() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlLink)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlLink))));
            }
            else {
                
                #line 11 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
                
                #line default
                #line hidden
            }
            
            #line 11 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "preconnect");
            
            #line default
            #line hidden
            
            #line 11 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl.Href = "https://fonts.googleapis.com";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        384,
                        61,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control9() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlLink)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlLink))));
            }
            else {
                
                #line 12 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
                
                #line default
                #line hidden
            }
            
            #line 12 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "preconnect");
            
            #line default
            #line hidden
            
            #line 12 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl.Href = "https://fonts.gstatic.com";
            
            #line default
            #line hidden
            
            #line 12 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("crossorigin", "crossorigin");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        455,
                        84,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control10() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlLink)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlLink))));
            }
            else {
                
                #line 13 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
                
                #line default
                #line hidden
            }
            
            #line 13 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl.Href = "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&displ" +
                "ay=swap";
            
            #line default
            #line hidden
            
            #line 13 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        549,
                        134,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control11() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n        <script src=\"https://code.iconify.design/iconify-icon/3.0.0/iconify-ico" +
                    "n.min.js\"></script>\r\n        <style>\r\n            *,\r\n            *::before,\r\n  " +
                    "          *::after {\r\n                box-sizing: border-box;\r\n                m" +
                    "argin: 0;\r\n                padding: 0;\r\n            }\r\n\r\n            body {\r\n   " +
                    "             font-family: \'Inter\', sans-serif;\r\n                min-height: 100v" +
                    "h;\r\n                display: flex;\r\n                background: #0a0f1e;\r\n      " +
                    "          overflow: hidden;\r\n            }\r\n\r\n            /* ── Left Art Panel ─" +
                    "─────────────────────────────── */\r\n            .art-panel {\r\n                fl" +
                    "ex: 1;\r\n                background: linear-gradient(135deg, #1e1b4b 0%, #312e81 " +
                    "40%, #4c1d95 100%);\r\n                position: relative;\r\n                displa" +
                    "y: flex;\r\n                flex-direction: column;\r\n                align-items: " +
                    "center;\r\n                justify-content: center;\r\n                padding: 60px" +
                    ";\r\n                overflow: hidden;\r\n            }\r\n\r\n            .art-panel::b" +
                    "efore {\r\n                content: \'\';\r\n                position: absolute;\r\n    " +
                    "            width: 500px;\r\n                height: 500px;\r\n                borde" +
                    "r-radius: 50%;\r\n                background: radial-gradient(circle, rgba(139, 92" +
                    ", 246, .25) 0%, transparent 70%);\r\n                top: -100px;\r\n               " +
                    " right: -100px;\r\n            }\r\n\r\n            .art-panel::after {\r\n             " +
                    "   content: \'\';\r\n                position: absolute;\r\n                width: 350" +
                    "px;\r\n                height: 350px;\r\n                border-radius: 50%;\r\n      " +
                    "          background: radial-gradient(circle, rgba(99, 102, 241, .2) 0%, transpa" +
                    "rent 70%);\r\n                bottom: -80px;\r\n                left: 60px;\r\n       " +
                    "     }\r\n\r\n            .art-logo {\r\n                display: flex;\r\n             " +
                    "   align-items: center;\r\n                gap: 14px;\r\n                margin-bott" +
                    "om: 56px;\r\n                z-index: 1;\r\n            }\r\n\r\n            .art-logo-i" +
                    "con {\r\n                width: 50px;\r\n                height: 50px;\r\n            " +
                    "    background: linear-gradient(135deg, #8b5cf6, #6366f1);\r\n                bord" +
                    "er-radius: 14px;\r\n                display: flex;\r\n                align-items: c" +
                    "enter;\r\n                justify-content: center;\r\n                box-shadow: 0 " +
                    "8px 24px rgba(139, 92, 246, .4);\r\n            }\r\n\r\n            .art-logo-text {\r" +
                    "\n                font-size: 26px;\r\n                font-weight: 800;\r\n          " +
                    "      color: white;\r\n            }\r\n\r\n            .art-tagline {\r\n              " +
                    "  font-size: 38px;\r\n                font-weight: 800;\r\n                color: wh" +
                    "ite;\r\n                line-height: 1.2;\r\n                text-align: center;\r\n  " +
                    "              margin-bottom: 20px;\r\n                z-index: 1;\r\n            }\r\n" +
                    "\r\n            .art-sub {\r\n                font-size: 16px;\r\n                colo" +
                    "r: rgba(255, 255, 255, .6);\r\n                text-align: center;\r\n              " +
                    "  z-index: 1;\r\n                max-width: 380px;\r\n            }\r\n\r\n            ." +
                    "art-badges {\r\n                display: flex;\r\n                gap: 12px;\r\n      " +
                    "          margin-top: 48px;\r\n                z-index: 1;\r\n                flex-w" +
                    "rap: wrap;\r\n                justify-content: center;\r\n            }\r\n\r\n         " +
                    "   .art-badge {\r\n                background: rgba(255, 255, 255, .1);\r\n         " +
                    "       border: 1px solid rgba(255, 255, 255, .15);\r\n                border-radiu" +
                    "s: 100px;\r\n                padding: 8px 18px;\r\n                font-size: 13px;\r" +
                    "\n                color: rgba(255, 255, 255, .8);\r\n                display: flex;" +
                    "\r\n                align-items: center;\r\n                gap: 7px;\r\n            }" +
                    "\r\n\r\n            /* ── Right Login Panel ──────────────────────────── */\r\n       " +
                    "     .login-panel {\r\n                width: 480px;\r\n                flex-shrink:" +
                    " 0;\r\n                background: #0d1117;\r\n                display: flex;\r\n     " +
                    "           align-items: center;\r\n                justify-content: center;\r\n     " +
                    "           padding: 48px 40px;\r\n                border-left: 1px solid rgba(255," +
                    " 255, 255, .06);\r\n            }\r\n\r\n            .login-box {\r\n                wid" +
                    "th: 100%;\r\n            }\r\n\r\n            .login-header {\r\n                margin-" +
                    "bottom: 36px;\r\n            }\r\n\r\n            .login-title {\r\n                font" +
                    "-size: 28px;\r\n                font-weight: 800;\r\n                color: #f1f5f9;" +
                    "\r\n                margin-bottom: 6px;\r\n            }\r\n\r\n            .login-desc " +
                    "{\r\n                font-size: 14px;\r\n                color: #64748b;\r\n          " +
                    "  }\r\n\r\n            .form-group {\r\n                margin-bottom: 20px;\r\n        " +
                    "    }\r\n\r\n            .form-label {\r\n                display: block;\r\n           " +
                    "     font-size: 13px;\r\n                font-weight: 600;\r\n                color:" +
                    " #94a3b8;\r\n                margin-bottom: 8px;\r\n                letter-spacing: " +
                    ".04em;\r\n                text-transform: uppercase;\r\n            }\r\n\r\n           " +
                    " .input-wrapper {\r\n                position: relative;\r\n            }\r\n\r\n       " +
                    "     .input-icon {\r\n                position: absolute;\r\n                left: 1" +
                    "4px;\r\n                top: 50%;\r\n                transform: translateY(-50%);\r\n " +
                    "               color: #475569;\r\n                display: flex;\r\n            }\r\n\r" +
                    "\n            .form-input {\r\n                width: 100%;\r\n                backgr" +
                    "ound: #1e2533;\r\n                border: 1.5px solid #2d3748;\r\n                bo" +
                    "rder-radius: 12px;\r\n                padding: 14px 14px 14px 44px;\r\n             " +
                    "   font-size: 14px;\r\n                color: #f1f5f9;\r\n                font-famil" +
                    "y: \'Inter\', sans-serif;\r\n                transition: border-color .2s, box-shado" +
                    "w .2s;\r\n                outline: none;\r\n            }\r\n\r\n            .form-input" +
                    ":focus {\r\n                border-color: #7c3aed;\r\n                box-shadow: 0 " +
                    "0 0 3px rgba(124, 58, 237, .2);\r\n            }\r\n\r\n            .form-input::place" +
                    "holder {\r\n                color: #475569;\r\n            }\r\n\r\n            .btn-log" +
                    "in {\r\n                width: 100%;\r\n                background: linear-gradient(" +
                    "135deg, #7c3aed, #6366f1);\r\n                color: white;\r\n                borde" +
                    "r: none;\r\n                border-radius: 12px;\r\n                padding: 15px;\r\n" +
                    "                font-size: 15px;\r\n                font-weight: 700;\r\n           " +
                    "     font-family: \'Inter\', sans-serif;\r\n                cursor: pointer;\r\n      " +
                    "          transition: transform .15s, box-shadow .15s, opacity .15s;\r\n          " +
                    "      box-shadow: 0 8px 24px rgba(124, 58, 237, .35);\r\n                margin-to" +
                    "p: 8px;\r\n                display: flex;\r\n                align-items: center;\r\n " +
                    "               justify-content: center;\r\n                gap: 8px;\r\n            " +
                    "}\r\n\r\n            .btn-login:hover {\r\n                transform: translateY(-2px)" +
                    ";\r\n                box-shadow: 0 12px 32px rgba(124, 58, 237, .45);\r\n           " +
                    " }\r\n\r\n            .btn-login:active {\r\n                transform: translateY(0);" +
                    "\r\n            }\r\n\r\n            .error-msg {\r\n                background: rgba(23" +
                    "9, 68, 68, .12);\r\n                border: 1px solid rgba(239, 68, 68, .25);\r\n   " +
                    "             border-radius: 10px;\r\n                padding: 12px 16px;\r\n        " +
                    "        font-size: 13px;\r\n                color: #f87171;\r\n                margi" +
                    "n-bottom: 20px;\r\n                display: flex;\r\n                align-items: ce" +
                    "nter;\r\n                gap: 8px;\r\n            }\r\n\r\n            .back-link {\r\n   " +
                    "             display: block;\r\n                text-align: center;\r\n             " +
                    "   margin-top: 28px;\r\n                font-size: 13px;\r\n                color: #" +
                    "475569;\r\n                text-decoration: none;\r\n                transition: col" +
                    "or .2s;\r\n            }\r\n\r\n            .back-link:hover {\r\n                color:" +
                    " #7c3aed;\r\n            }\r\n\r\n            .security-note {\r\n                displa" +
                    "y: flex;\r\n                align-items: center;\r\n                gap: 8px;\r\n     " +
                    "           margin-top: 32px;\r\n                padding: 12px 16px;\r\n             " +
                    "   background: rgba(16, 185, 129, .08);\r\n                border: 1px solid rgba(" +
                    "16, 185, 129, .15);\r\n                border-radius: 10px;\r\n                font-" +
                    "size: 12px;\r\n                color: #34d399;\r\n            }\r\n\r\n            @medi" +
                    "a (max-width: 900px) {\r\n                .art-panel {\r\n                    displa" +
                    "y: none;\r\n                }\r\n\r\n                .login-panel {\r\n                 " +
                    "   width: 100%;\r\n                    border: none;\r\n                    backgrou" +
                    "nd: #0a0f1e;\r\n                }\r\n            }\r\n        </style>\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        683,
                        8551,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl1;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl2;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl2 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl3;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl3 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl4;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl4 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl5;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl5 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl6;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl6 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl7 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        191,
                        9050,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control12() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n    <body>\r\n        ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        9241,
                        24,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control14() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n            <div style=\"display:flex; min-height:100vh;\">\r\n\r\n                <!" +
                    "-- ── Art Panel ── -->\r\n                <div class=\"art-panel\">\r\n               " +
                    "     <div class=\"art-logo\">\r\n                        <div class=\"art-logo-icon\">" +
                    "\r\n                            <iconify-icon icon=\"lucide:landmark\" style=\"font-s" +
                    "ize:26px; color:white\"></iconify-icon>\r\n                        </div>\r\n        " +
                    "                <span class=\"art-logo-text\">NeoBank</span>\r\n                    " +
                    "</div>\r\n                    <h1 class=\"art-tagline\">Admin Control<br />Centre</h" +
                    "1>\r\n                    <p class=\"art-sub\">Manage KYC approvals, monitor account" +
                    "s, and oversee all banking operations from\r\n                        one place.</" +
                    "p>\r\n                    <div class=\"art-badges\">\r\n                        <div c" +
                    "lass=\"art-badge\">\r\n                            <iconify-icon icon=\"lucide:shield" +
                    "-check\" style=\"font-size:14px\"></iconify-icon>\r\n                            KYC " +
                    "Management\r\n                        </div>\r\n                        <div class=\"" +
                    "art-badge\">\r\n                            <iconify-icon icon=\"lucide:users\" style" +
                    "=\"font-size:14px\"></iconify-icon>\r\n                            User Oversight\r\n " +
                    "                       </div>\r\n                        <div class=\"art-badge\">\r\n" +
                    "                            <iconify-icon icon=\"lucide:activity\" style=\"font-siz" +
                    "e:14px\"></iconify-icon>\r\n                            Live Monitoring\r\n          " +
                    "              </div>\r\n                    </div>\r\n                </div>\r\n\r\n    " +
                    "            <!-- ── Login Panel ── -->\r\n                <div class=\"login-panel\"" +
                    ">\r\n                    <div class=\"login-box\">\r\n                        <div cla" +
                    "ss=\"login-header\">\r\n                            <h2 class=\"login-title\">Admin Si" +
                    "gn In</h2>\r\n                            <p class=\"login-desc\">Enter your credent" +
                    "ials to access the admin panel</p>\r\n                        </div>\r\n\r\n          " +
                    "              ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        9286,
                        1935,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control15() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                            <div class=""error-msg"">
                                <iconify-icon icon=""lucide:alert-triangle"" style=""font-size:16px""></iconify-icon>
                                <span id=""errText""></span>
                            </div>
                        ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        11277,
                        290,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllblError() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.Label)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.Label))));
            }
            else {
                
                #line 335 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
                @__ctrl = new global::System.Web.UI.WebControls.Label();
                
                #line default
                #line hidden
            }
            this.lblError = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 335 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl.ID = "lblError";
            
            #line default
            #line hidden
            
            #line 335 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 335 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl1 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 335 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        11221,
                        358,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control16() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"

                        <div class=""form-group"">
                            <label class=""form-label"">Admin Email</label>
                            <div class=""input-wrapper"">
                                <span class=""input-icon"">
                                    <iconify-icon icon=""lucide:mail"" style=""font-size:18px""></iconify-icon>
                                </span>
                                ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        11579,
                        427,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtEmail() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.TextBox)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.TextBox))));
            }
            else {
                
                #line 348 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
                @__ctrl = new global::System.Web.UI.WebControls.TextBox();
                
                #line default
                #line hidden
            }
            this.txtEmail = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 348 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl.ID = "txtEmail";
            
            #line default
            #line hidden
            
            #line 348 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl.CssClass = "form-input";
            
            #line default
            #line hidden
            
            #line 348 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "admin@neobank.com");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        12006,
                        147,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control17() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                            </div>
                        </div>

                        <div class=""form-group"">
                            <label class=""form-label"">Password</label>
                            <div class=""input-wrapper"">
                                <span class=""input-icon"">
                                    <iconify-icon icon=""lucide:lock"" style=""font-size:18px""></iconify-icon>
                                </span>
                                ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        12153,
                        492,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtPassword() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.TextBox)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.TextBox))));
            }
            else {
                
                #line 359 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
                @__ctrl = new global::System.Web.UI.WebControls.TextBox();
                
                #line default
                #line hidden
            }
            this.txtPassword = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 359 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl.ID = "txtPassword";
            
            #line default
            #line hidden
            
            #line 359 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            
            #line default
            #line hidden
            
            #line 359 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl.CssClass = "form-input";
            
            #line default
            #line hidden
            
            #line 359 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "••••••••");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        12645,
                        161,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control18() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                            </div>\r\n                        </div>\r\n\r\n         " +
                    "               ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        12806,
                        96,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnLogin() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.Button)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.Button))));
            }
            else {
                
                #line 364 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
                @__ctrl = new global::System.Web.UI.WebControls.Button();
                
                #line default
                #line hidden
            }
            this.btnLogin = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 364 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl.ID = "btnLogin";
            
            #line default
            #line hidden
            
            #line 364 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl.CssClass = "btn-login";
            
            #line default
            #line hidden
            
            #line 364 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl.Text = "Sign In to Admin Panel";
            
            #line default
            #line hidden
            
            #line 364 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl.Click -= new System.EventHandler(this.btnLogin_Click);
            
            #line default
            #line hidden
            
            #line 364 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl.Click += new System.EventHandler(this.btnLogin_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        12902,
                        148,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control19() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"

                        <div class=""security-note"">
                            <iconify-icon icon=""lucide:lock"" style=""font-size:14px""></iconify-icon>
                            Secured with end-to-end encryption. Unauthorised access is prohibited.
                        </div>

                        <a href=""Login.aspx"" class=""back-link"">← Back to User Login</a>
                    </div>
                </div>

            </div>
        ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        13050,
                        463,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControl__control13() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlForm)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlForm))));
            }
            else {
                
                #line 297 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
                
                #line default
                #line hidden
            }
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 297 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl1 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 297 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl2;
            
            #line 297 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl2 = this.@__BuildControllblError();
            
            #line default
            #line hidden
            
            #line 297 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 297 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl3 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            
            #line 297 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            
            #line 297 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl4 = this.@__BuildControltxtEmail();
            
            #line default
            #line hidden
            
            #line 297 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 297 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl5 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            
            #line 297 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl6;
            
            #line 297 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl6 = this.@__BuildControltxtPassword();
            
            #line default
            #line hidden
            
            #line 297 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 297 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl7 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            
            #line 297 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl8;
            
            #line 297 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl8 = this.@__BuildControlbtnLogin();
            
            #line default
            #line hidden
            
            #line 297 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl9;
            
            #line 297 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl9 = this.@__BuildControl__control19();
            
            #line default
            #line hidden
            
            #line 297 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        9265,
                        4255,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control20() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    </body>\r\n\r\n    </html>");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        13520,
                        28,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(adminlogin_aspx @__ctrl) {
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl2;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl2 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl3 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl4;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl4 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__ctrl5 = this.@__BuildControl__control20();
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AdminLogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.adminlogin_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -1332342018;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
