#pragma checksum "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx" "{8829d00f-11b8-4213-878b-770e8597ac16}" "7778E718C5156976C4CFA40E6080B1E3B0D749079B7A1DCD541A9D5DFC26A7A3"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 448 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 13 "D:\Project\OnlineBankingTransactionSystem\web.config"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 448 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 448 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 448 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 448 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class addbeneficiary_aspx : global::OnlineBankingTransactionSystem.AddBeneficiary, System.Web.SessionState.IRequiresSessionState, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.addbeneficiary_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public addbeneficiary_aspx() {
            string[] dependencies;
            ((global::OnlineBankingTransactionSystem.AddBeneficiary)(this)).AppRelativeVirtualPath = "~/AddBeneficiary.aspx";
            if ((global::ASP.addbeneficiary_aspx.@__initialized == false)) {
                dependencies = new string[1];
                dependencies[0] = "~/AddBeneficiary.aspx";
                global::ASP.addbeneficiary_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.addbeneficiary_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(this.Context.ApplicationInstance));
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n    <!DOCTYPE html>\r\n    <html>\r\n\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        146,
                        43,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.WebTools.BrowserLink.Runtime.WebForms.TraceHelpers, Microsoft.WebTools." +
                    "BrowserLink.Tracing, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f1" +
                    "1d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.addbeneficiary_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.addbeneficiary_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlMeta)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlMeta))));
            }
            else {
                
                #line 8 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
                
                #line default
                #line hidden
            }
            
            #line 8 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("charset", "UTF-8");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        220,
                        24,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control5() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlMeta)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlMeta))));
            }
            else {
                
                #line 9 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
                
                #line default
                #line hidden
            }
            
            #line 9 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.Name = "viewport";
            
            #line default
            #line hidden
            
            #line 9 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.Content = "width=device-width, initial-scale=1.0";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        254,
                        72,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control7() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("Add Beneficiary - Online Banking");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        343,
                        32,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control6() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlTitle)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlTitle))));
            }
            else {
                
                #line 10 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
                
                #line default
                #line hidden
            }
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 10 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl1 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 10 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        336,
                        47,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control8() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n        <!-- Google Fonts -->\r\n        ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        383,
                        43,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control9() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlLink)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlLink))));
            }
            else {
                
                #line 13 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
                
                #line default
                #line hidden
            }
            
            #line 13 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "preconnect");
            
            #line default
            #line hidden
            
            #line 13 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.Href = "https://fonts.googleapis.com";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        426,
                        61,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control10() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlLink)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlLink))));
            }
            else {
                
                #line 14 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
                
                #line default
                #line hidden
            }
            
            #line 14 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "preconnect");
            
            #line default
            #line hidden
            
            #line 14 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.Href = "https://fonts.gstatic.com";
            
            #line default
            #line hidden
            
            #line 14 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("crossorigin", "");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        497,
                        70,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control11() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlLink)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlLink))));
            }
            else {
                
                #line 15 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
                
                #line default
                #line hidden
            }
            
            #line 15 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.Href = "https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;8" +
                "00;900&display=swap";
            
            #line default
            #line hidden
            
            #line 15 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        577,
                        159,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control12() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n        <!-- Iconify Icons -->\r\n        <script src=\"https://code.iconify.des" +
                    "ign/iconify-icon/3.0.0/iconify-icon.min.js\"></script>\r\n\r\n        <style>\r\n      " +
                    "      :root {\r\n                --background: #f8f9fa;\r\n                --foregro" +
                    "und: #0f172a;\r\n                --card: #ffffff;\r\n                --card-foregrou" +
                    "nd: #0f172a;\r\n                --primary: #4f46e5;\r\n                --primary-for" +
                    "eground: #ffffff;\r\n                --secondary: #f1f5f9;\r\n                --seco" +
                    "ndary-foreground: #1e293b;\r\n                --muted: #f1f5f9;\r\n                -" +
                    "-muted-foreground: #64748b;\r\n                --success: #10b981;\r\n              " +
                    "  --success-foreground: #ffffff;\r\n                --destructive: #ef4444;\r\n     " +
                    "           --destructive-foreground: #ffffff;\r\n                --border: #e2e8f0" +
                    ";\r\n                --radius-sm: 4px;\r\n                --radius-md: 8px;\r\n       " +
                    "         --radius-lg: 12px;\r\n                --radius-xl: 16px;\r\n            }\r\n" +
                    "\r\n            * {\r\n                box-sizing: border-box;\r\n                marg" +
                    "in: 0;\r\n                padding: 0;\r\n            }\r\n\r\n            body {\r\n      " +
                    "          font-family: \'Inter\', -apple-system, BlinkMacSystemFont, \"Segoe UI\", R" +
                    "oboto, sans-serif;\r\n                background-color: var(--background);\r\n      " +
                    "          color: var(--foreground);\r\n                height: 100vh;\r\n           " +
                    "     overflow: hidden;\r\n            }\r\n\r\n            .dashboard-wrapper {\r\n     " +
                    "           display: flex;\r\n                height: 100vh;\r\n                overf" +
                    "low: hidden;\r\n            }\r\n\r\n            /* Sidebar Styles */\r\n            .si" +
                    "debar {\r\n                width: 260px;\r\n                background-color: var(--" +
                    "card);\r\n                border-right: 1px solid var(--border);\r\n                " +
                    "display: flex;\r\n                flex-direction: column;\r\n                height:" +
                    " 100%;\r\n                flex-shrink: 0;\r\n            }\r\n\r\n            .sidebar-h" +
                    "eader {\r\n                height: 70px;\r\n                display: flex;\r\n        " +
                    "        align-items: center;\r\n                padding: 0 24px;\r\n            }\r\n\r" +
                    "\n            .brand {\r\n                font-size: 20px;\r\n                font-we" +
                    "ight: 700;\r\n                color: var(--primary);\r\n                display: fle" +
                    "x;\r\n                align-items: center;\r\n                gap: 8px;\r\n           " +
                    " }\r\n\r\n            .brand-icon {\r\n                width: 32px;\r\n                h" +
                    "eight: 32px;\r\n                background: var(--primary);\r\n                borde" +
                    "r-radius: 8px;\r\n                display: flex;\r\n                align-items: cen" +
                    "ter;\r\n                justify-content: center;\r\n                color: white;\r\n " +
                    "           }\r\n\r\n            .nav-menu {\r\n                flex: 1;\r\n             " +
                    "   padding: 24px 16px;\r\n                display: flex;\r\n                flex-dir" +
                    "ection: column;\r\n                gap: 4px;\r\n                overflow-y: auto;\r\n " +
                    "           }\r\n\r\n            .nav-item {\r\n                display: flex;\r\n       " +
                    "         align-items: center;\r\n                gap: 12px;\r\n                paddi" +
                    "ng: 12px 16px;\r\n                border-radius: var(--radius-md);\r\n              " +
                    "  color: var(--muted-foreground);\r\n                font-size: 14px;\r\n           " +
                    "     font-weight: 500;\r\n                text-decoration: none;\r\n                " +
                    "cursor: pointer;\r\n                transition: all 0.2s;\r\n            }\r\n\r\n      " +
                    "      .nav-item:hover {\r\n                background-color: var(--secondary);\r\n  " +
                    "          }\r\n\r\n            .nav-item.active {\r\n                background-color:" +
                    " var(--primary);\r\n                color: var(--primary-foreground);\r\n           " +
                    " }\r\n\r\n            /* Main Content */\r\n            .main-content {\r\n             " +
                    "   flex: 1;\r\n                display: flex;\r\n                flex-direction: col" +
                    "umn;\r\n                height: 100%;\r\n                overflow: hidden;\r\n        " +
                    "    }\r\n\r\n            .top-bar {\r\n                height: 70px;\r\n                " +
                    "background-color: var(--card);\r\n                border-bottom: 1px solid var(--b" +
                    "order);\r\n                display: flex;\r\n                align-items: center;\r\n " +
                    "               justify-content: space-between;\r\n                padding: 0 32px;" +
                    "\r\n                flex-shrink: 0;\r\n            }\r\n\r\n            .page-title {\r\n " +
                    "               font-size: 18px;\r\n                font-weight: 600;\r\n            " +
                    "    color: var(--foreground);\r\n            }\r\n\r\n            .top-actions {\r\n    " +
                    "            display: flex;\r\n                align-items: center;\r\n              " +
                    "  gap: 16px;\r\n            }\r\n\r\n            .back-btn {\r\n                backgrou" +
                    "nd-color: var(--secondary);\r\n                color: var(--foreground);\r\n        " +
                    "        border: none;\r\n                padding: 8px 16px;\r\n                borde" +
                    "r-radius: var(--radius-md);\r\n                font-size: 13px;\r\n                f" +
                    "ont-weight: 500;\r\n                cursor: pointer;\r\n                transition: " +
                    "all 0.2s;\r\n                text-decoration: none;\r\n                display: flex" +
                    ";\r\n                align-items: center;\r\n                gap: 6px;\r\n            " +
                    "}\r\n\r\n            .back-btn:hover {\r\n                background-color: var(--mute" +
                    "d);\r\n            }\r\n\r\n            /* Scrollable Area */\r\n            .page-scrol" +
                    "l {\r\n                flex: 1;\r\n                overflow-y: auto;\r\n              " +
                    "  padding: 32px;\r\n            }\r\n\r\n            .page-container {\r\n              " +
                    "  max-width: 600px;\r\n                margin: 0 auto;\r\n            }\r\n\r\n         " +
                    "   /* Form Card */\r\n            .form-card {\r\n                background-color: " +
                    "var(--card);\r\n                border: 1px solid var(--border);\r\n                " +
                    "border-radius: var(--radius-xl);\r\n                padding: 40px;\r\n              " +
                    "  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);\r\n            }\r\n\r\n            .form-" +
                    "header {\r\n                text-align: center;\r\n                margin-bottom: 32" +
                    "px;\r\n            }\r\n\r\n            .form-icon {\r\n                width: 64px;\r\n  " +
                    "              height: 64px;\r\n                background: linear-gradient(135deg," +
                    " #4f46e5 0%, #3730a3 100%);\r\n                border-radius: 16px;\r\n             " +
                    "   display: flex;\r\n                align-items: center;\r\n                justify" +
                    "-content: center;\r\n                margin: 0 auto 16px;\r\n                color: " +
                    "white;\r\n            }\r\n\r\n            .form-title {\r\n                font-size: 2" +
                    "4px;\r\n                font-weight: 700;\r\n                margin-bottom: 8px;\r\n  " +
                    "              color: var(--foreground);\r\n            }\r\n\r\n            .form-subt" +
                    "itle {\r\n                font-size: 14px;\r\n                color: var(--muted-for" +
                    "eground);\r\n            }\r\n\r\n            /* Form Elements */\r\n            .form-g" +
                    "roup {\r\n                margin-bottom: 24px;\r\n            }\r\n\r\n            .form" +
                    "-label {\r\n                display: block;\r\n                font-size: 14px;\r\n   " +
                    "             font-weight: 500;\r\n                margin-bottom: 8px;\r\n           " +
                    "     color: var(--foreground);\r\n            }\r\n\r\n            .form-input {\r\n    " +
                    "            width: 100%;\r\n                padding: 12px 16px;\r\n                b" +
                    "order: 1px solid var(--border);\r\n                border-radius: var(--radius-md)" +
                    ";\r\n                font-size: 14px;\r\n                font-family: \'Inter\', sans-" +
                    "serif;\r\n                transition: all 0.2s;\r\n            }\r\n\r\n            .for" +
                    "m-input:focus {\r\n                outline: none;\r\n                border-color: v" +
                    "ar(--primary);\r\n                box-shadow: 0 0 0 3px rgba(79, 70, 229, 0.1);\r\n " +
                    "           }\r\n\r\n            .form-hint {\r\n                font-size: 12px;\r\n    " +
                    "            color: var(--muted-foreground);\r\n                margin-top: 6px;\r\n " +
                    "           }\r\n\r\n            /* Buttons */\r\n            .btn {\r\n                p" +
                    "adding: 12px 24px;\r\n                border: none;\r\n                border-radius" +
                    ": var(--radius-md);\r\n                font-size: 14px;\r\n                font-weig" +
                    "ht: 600;\r\n                cursor: pointer;\r\n                transition: all 0.2s" +
                    ";\r\n            }\r\n\r\n            .btn-primary {\r\n                background-color" +
                    ": var(--primary);\r\n                color: var(--primary-foreground);\r\n          " +
                    "  }\r\n\r\n            .btn-primary:hover {\r\n                background-color: #4338" +
                    "ca;\r\n            }\r\n\r\n            .btn-success {\r\n                background-col" +
                    "or: var(--success);\r\n                color: var(--success-foreground);\r\n        " +
                    "    }\r\n\r\n            .btn-success:hover {\r\n                background-color: #05" +
                    "9669;\r\n            }\r\n\r\n            .btn-secondary {\r\n                background" +
                    "-color: var(--secondary);\r\n                color: var(--secondary-foreground);\r\n" +
                    "            }\r\n\r\n            .btn-secondary:hover {\r\n                background-" +
                    "color: var(--muted);\r\n            }\r\n\r\n            .button-group {\r\n            " +
                    "    display: flex;\r\n                gap: 12px;\r\n                margin-top: 32px" +
                    ";\r\n            }\r\n\r\n            .button-group .btn {\r\n                flex: 1;\r\n" +
                    "            }\r\n\r\n            /* Alerts */\r\n            .alert {\r\n               " +
                    " padding: 16px;\r\n                border-radius: var(--radius-md);\r\n             " +
                    "   margin-top: 16px;\r\n                display: none;\r\n            }\r\n\r\n         " +
                    "   .alert.show {\r\n                display: block;\r\n            }\r\n\r\n            " +
                    ".alert-success {\r\n                background-color: #ecfdf5;\r\n                bo" +
                    "rder: 1px solid var(--success);\r\n                color: #047857;\r\n            }\r" +
                    "\n\r\n            .alert-error {\r\n                background-color: #fee2e2;\r\n     " +
                    "           border: 1px solid var(--destructive);\r\n                color: #991b1b" +
                    ";\r\n            }\r\n\r\n            .alert-title {\r\n                font-weight: 600" +
                    ";\r\n                margin-bottom: 4px;\r\n            }\r\n\r\n            /* Responsi" +
                    "ve */\r\n            @media (max-width: 768px) {\r\n                .sidebar {\r\n    " +
                    "                position: fixed;\r\n                    left: -260px;\r\n           " +
                    "         z-index: 1000;\r\n                    transition: left 0.3s;\r\n           " +
                    "     }\r\n\r\n                .sidebar.active {\r\n                    left: 0;\r\n     " +
                    "           }\r\n\r\n                .form-card {\r\n                    padding: 24px;" +
                    "\r\n                }\r\n\r\n                .button-group {\r\n                    flex" +
                    "-direction: column;\r\n                }\r\n            }\r\n        </style>\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        736,
                        10238,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl1;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl2;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl2 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl3;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl3 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl4;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl4 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl5;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl5 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl6;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl6 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl7;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl7 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl8;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl8 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        189,
                        10792,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control13() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n    <body>\r\n        ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        10981,
                        24,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control15() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n            <div class=\"dashboard-wrapper\">\r\n                <!-- Sidebar -->\r\n" +
                    "                <aside class=\"sidebar\">\r\n                    <div class=\"sidebar" +
                    "-header\">\r\n                        <div class=\"brand\">\r\n                        " +
                    "    <div class=\"brand-icon\">\r\n                                <iconify-icon icon" +
                    "=\"lucide:landmark\" style=\"font-size: 20px\"></iconify-icon>\r\n                    " +
                    "        </div>\r\n                            NeoBank\r\n                        </d" +
                    "iv>\r\n                    </div>\r\n\r\n                    <nav class=\"nav-menu\">\r\n " +
                    "                       <a href=\"Dashboard.aspx\" class=\"nav-item\">\r\n             " +
                    "               <iconify-icon icon=\"lucide:layout-dashboard\" style=\"font-size: 20" +
                    "px\"></iconify-icon>\r\n                            Dashboard\r\n                    " +
                    "    </a>\r\n                        <a href=\"BillPayment.aspx\" class=\"nav-item\">\r\n" +
                    "                            <iconify-icon icon=\"lucide:file-text\" style=\"font-si" +
                    "ze: 20px\"></iconify-icon>\r\n                            Bill Payments\r\n          " +
                    "              </a>\r\n                        <a href=\"BillPayment.aspx\" class=\"na" +
                    "v-item\">\r\n                            <iconify-icon icon=\"lucide:smartphone\" sty" +
                    "le=\"font-size: 20px\"></iconify-icon>\r\n                            Mobile / DTH\r\n" +
                    "                        </a>\r\n                        <a href=\"SendMoney.aspx\" c" +
                    "lass=\"nav-item\">\r\n                            <iconify-icon icon=\"lucide:send\" s" +
                    "tyle=\"font-size: 20px\"></iconify-icon>\r\n                            Send Money\r\n" +
                    "                        </a>\r\n                        <a href=\"AddMoney.aspx\" cl" +
                    "ass=\"nav-item\">\r\n                            <iconify-icon icon=\"lucide:plus-cir" +
                    "cle\" style=\"font-size: 20px\"></iconify-icon>\r\n                            Add Mo" +
                    "ney\r\n                        </a>\r\n                        <a href=\"TransactionH" +
                    "istory.aspx\" class=\"nav-item\">\r\n                            <iconify-icon icon=\"" +
                    "lucide:history\" style=\"font-size: 20px\"></iconify-icon>\r\n                       " +
                    "     Transactions\r\n                        </a>\r\n                        <a href" +
                    "=\"ManageBeneficiaries.aspx\" class=\"nav-item active\">\r\n                          " +
                    "  <iconify-icon icon=\"lucide:users\" style=\"font-size: 20px\"></iconify-icon>\r\n   " +
                    "                         Beneficiaries\r\n                        </a>\r\n          " +
                    "          </nav>\r\n                </aside>\r\n\r\n                <!-- Main Content " +
                    "-->\r\n                <main class=\"main-content\">\r\n                    <!-- Heade" +
                    "r -->\r\n                    <header class=\"top-bar\">\r\n                        <di" +
                    "v class=\"page-title\">Add Beneficiary</div>\r\n                        <div class=\"" +
                    "top-actions\">\r\n                            <a href=\"ManageBeneficiaries.aspx\" cl" +
                    "ass=\"back-btn\">\r\n                                <iconify-icon icon=\"lucide:arro" +
                    "w-left\" style=\"font-size: 16px\"></iconify-icon>\r\n                               " +
                    " Back to Beneficiaries\r\n                            </a>\r\n                      " +
                    "  </div>\r\n                    </header>\r\n\r\n                    <!-- Body -->\r\n  " +
                    "                  <div class=\"page-scroll\">\r\n                        <div class=" +
                    "\"page-container\">\r\n                            <div class=\"form-card\">\r\n        " +
                    "                        <div class=\"form-header\">\r\n                             " +
                    "       <div class=\"form-icon\">\r\n                                        <iconify" +
                    "-icon icon=\"lucide:user-plus\" style=\"font-size: 32px\"></iconify-icon>\r\n         " +
                    "                           </div>\r\n                                    <div clas" +
                    "s=\"form-title\">Add New Beneficiary</div>\r\n                                    <d" +
                    "iv class=\"form-subtitle\">Add a recipient to your saved beneficiaries for quick\r\n" +
                    "                                        transfers</div>\r\n                       " +
                    "         </div>\r\n\r\n                                <!-- Recipient Input -->\r\n   " +
                    "                             <div class=\"form-group\">\r\n                         " +
                    "           <label class=\"form-label\">Recipient Email / Mobile / UPI ID</label>\r\n" +
                    "                                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        11026,
                        4037,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtRecipient() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.TextBox)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.TextBox))));
            }
            else {
                
                #line 448 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
                @__ctrl = new global::System.Web.UI.WebControls.TextBox();
                
                #line default
                #line hidden
            }
            this.txtRecipient = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 448 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.ID = "txtRecipient";
            
            #line default
            #line hidden
            
            #line 448 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.CssClass = "form-input";
            
            #line default
            #line hidden
            
            #line 448 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Enter email, mobile, or UPI ID");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        15063,
                        168,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control16() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                                    <div class=""form-hint"">Enter the recipient's registered email, mobile number, or UPI
                                        ID</div>
                                </div>

                                <!-- Verify Button -->
                                ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        15231,
                        304,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnVerify() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.Button)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.Button))));
            }
            else {
                
                #line 455 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
                @__ctrl = new global::System.Web.UI.WebControls.Button();
                
                #line default
                #line hidden
            }
            this.btnVerify = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 455 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.ID = "btnVerify";
            
            #line default
            #line hidden
            
            #line 455 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.Text = "Verify Recipient";
            
            #line default
            #line hidden
            
            #line 455 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.CssClass = "btn btn-success";
            
            #line default
            #line hidden
            
            #line 455 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.Click -= new System.EventHandler(this.btnVerify_Click);
            
            #line default
            #line hidden
            
            #line 455 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.Click += new System.EventHandler(this.btnVerify_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        15535,
                        158,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control17() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n                                <!-- Success Panel -->\r\n                     " +
                    "           ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        15693,
                        92,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control18() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                    <div class=\"alert-title\">âœ… Recipient Foun" +
                    "d</div>\r\n                                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        15864,
                        126,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllblRecipientName() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.Label)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.Label))));
            }
            else {
                
                #line 461 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
                @__ctrl = new global::System.Web.UI.WebControls.Label();
                
                #line default
                #line hidden
            }
            this.lblRecipientName = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 461 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.ID = "lblRecipientName";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        15990,
                        60,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control19() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        16050,
                        34,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlRecipientInfo() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.Panel)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.Panel))));
            }
            else {
                
                #line 459 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
                @__ctrl = new global::System.Web.UI.WebControls.Panel();
                
                #line default
                #line hidden
            }
            this.pnlRecipientInfo = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 459 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.ID = "pnlRecipientInfo";
            
            #line default
            #line hidden
            
            #line 459 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.CssClass = "alert alert-success";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 459 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl1 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 459 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl2;
            
            #line 459 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl2 = this.@__BuildControllblRecipientName();
            
            #line default
            #line hidden
            
            #line 459 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 459 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl3 = this.@__BuildControl__control19();
            
            #line default
            #line hidden
            
            #line 459 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        15785,
                        311,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control20() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n                                <!-- Error Panel -->\r\n                       " +
                    "         ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        16096,
                        90,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control21() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        16255,
                        38,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllblError() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.Label)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.Label))));
            }
            else {
                
                #line 466 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
                @__ctrl = new global::System.Web.UI.WebControls.Label();
                
                #line default
                #line hidden
            }
            this.lblError = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 466 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.ID = "lblError";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        16293,
                        52,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control22() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        16345,
                        34,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlError() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.Panel)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.Panel))));
            }
            else {
                
                #line 465 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
                @__ctrl = new global::System.Web.UI.WebControls.Panel();
                
                #line default
                #line hidden
            }
            this.pnlError = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 465 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.ID = "pnlError";
            
            #line default
            #line hidden
            
            #line 465 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.CssClass = "alert alert-error";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 465 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl1 = this.@__BuildControl__control21();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 465 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl2;
            
            #line 465 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl2 = this.@__BuildControllblError();
            
            #line default
            #line hidden
            
            #line 465 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 465 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl3 = this.@__BuildControl__control22();
            
            #line default
            #line hidden
            
            #line 465 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        16186,
                        205,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control23() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"

                                <!-- Nickname Input -->
                                <div class=""form-group"" style=""margin-top: 24px;"">
                                    <label class=""form-label"">Nickname (Optional)</label>
                                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        16391,
                        272,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtNickname() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.TextBox)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.TextBox))));
            }
            else {
                
                #line 472 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
                @__ctrl = new global::System.Web.UI.WebControls.TextBox();
                
                #line default
                #line hidden
            }
            this.txtNickname = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 472 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.ID = "txtNickname";
            
            #line default
            #line hidden
            
            #line 472 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.CssClass = "form-input";
            
            #line default
            #line hidden
            
            #line 472 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "e.g., Mom, John, Office Account");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        16663,
                        168,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control24() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                                    <div class=""form-hint"">Give this beneficiary a friendly name for easy identification
                                    </div>
                                </div>

                                <!-- Action Buttons -->
                                <div class=""button-group"">
                                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        16831,
                        363,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnSave() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.Button)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.Button))));
            }
            else {
                
                #line 480 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
                @__ctrl = new global::System.Web.UI.WebControls.Button();
                
                #line default
                #line hidden
            }
            this.btnSave = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 480 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.ID = "btnSave";
            
            #line default
            #line hidden
            
            #line 480 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.Text = "Save Beneficiary";
            
            #line default
            #line hidden
            
            #line 480 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.CssClass = "btn btn-primary";
            
            #line default
            #line hidden
            
            #line 480 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.Click -= new System.EventHandler(this.btnSave_Click);
            
            #line default
            #line hidden
            
            #line 480 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.Click += new System.EventHandler(this.btnSave_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        17194,
                        158,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control25() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        17352,
                        38,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnCancel() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.Button)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.Button))));
            }
            else {
                
                #line 482 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
                @__ctrl = new global::System.Web.UI.WebControls.Button();
                
                #line default
                #line hidden
            }
            this.btnCancel = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 482 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.ID = "btnCancel";
            
            #line default
            #line hidden
            
            #line 482 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.Text = "Cancel";
            
            #line default
            #line hidden
            
            #line 482 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.CssClass = "btn btn-secondary";
            
            #line default
            #line hidden
            
            #line 482 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.Click -= new System.EventHandler(this.btnCancel_Click);
            
            #line default
            #line hidden
            
            #line 482 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl.Click += new System.EventHandler(this.btnCancel_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        17390,
                        154,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control26() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                </div>\r\n                            </div>\r\n   " +
                    "                     </div>\r\n                    </div>\r\n                </main>" +
                    "\r\n            </div>\r\n        ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        17544,
                        191,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControl__control14() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlForm)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlForm))));
            }
            else {
                
                #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
                
                #line default
                #line hidden
            }
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl1 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl2 = this.@__BuildControltxtRecipient();
            
            #line default
            #line hidden
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl3 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl4;
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl4 = this.@__BuildControlbtnVerify();
            
            #line default
            #line hidden
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl5 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl6;
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl6 = this.@__BuildControlpnlRecipientInfo();
            
            #line default
            #line hidden
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl7 = this.@__BuildControl__control20();
            
            #line default
            #line hidden
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl8;
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl8 = this.@__BuildControlpnlError();
            
            #line default
            #line hidden
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl9;
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl9 = this.@__BuildControl__control23();
            
            #line default
            #line hidden
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl10;
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl10 = this.@__BuildControltxtNickname();
            
            #line default
            #line hidden
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl11;
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl11 = this.@__BuildControl__control24();
            
            #line default
            #line hidden
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl12;
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl12 = this.@__BuildControlbtnSave();
            
            #line default
            #line hidden
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl13;
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl13 = this.@__BuildControl__control25();
            
            #line default
            #line hidden
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl14;
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl14 = this.@__BuildControlbtnCancel();
            
            #line default
            #line hidden
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl14);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl15;
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl15 = this.@__BuildControl__control26();
            
            #line default
            #line hidden
            
            #line 374 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl15);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        11005,
                        6737,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control27() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    </body>\r\n\r\n    </html>");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        17742,
                        28,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(addbeneficiary_aspx @__ctrl) {
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl2;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl2 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl3 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl4;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl4 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__ctrl5 = this.@__BuildControl__control27();
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AddBeneficiary.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.addbeneficiary_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -223703888;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
