#pragma checksum "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx" "{8829d00f-11b8-4213-878b-770e8597ac16}" "5D9280741B6543E9CFA93EAFC20BAB78B758C3740666FD9324ABAF6263A205C8"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 46 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 13 "D:\Project\OnlineBankingTransactionSystem\web.config"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 46 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 46 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 46 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 46 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class myqr_aspx : global::OnlineBankingTransactionSystem.MyQR, System.Web.SessionState.IRequiresSessionState, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.myqr_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public myqr_aspx() {
            string[] dependencies;
            ((global::OnlineBankingTransactionSystem.MyQR)(this)).AppRelativeVirtualPath = "~/MyQR.aspx";
            if ((global::ASP.myqr_aspx.@__initialized == false)) {
                global::ASP.myqr_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[1];
                dependencies[0] = "~/MyQR.aspx";
                global::ASP.myqr_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.myqr_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(this.Context.ApplicationInstance));
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n    <!DOCTYPE html>\r\n    <html>\r\n\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        126,
                        43,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.WebTools.BrowserLink.Runtime.WebForms.TraceHelpers, Microsoft.WebTools." +
                    "BrowserLink.Tracing, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f1" +
                    "1d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.myqr_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.myqr_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control5() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("My QR Code");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        207,
                        10,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlTitle)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlTitle))));
            }
            else {
                
                #line 8 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
                
                #line default
                #line hidden
            }
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 8 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl1 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 8 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        200,
                        25,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control6() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlLink)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlLink))));
            }
            else {
                
                #line 9 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
                
                #line default
                #line hidden
            }
            
            #line 9 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl.Href = "Content/bootstrap.min.css";
            
            #line default
            #line hidden
            
            #line 9 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        235,
                        58,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control7() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlLink)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlLink))));
            }
            else {
                
                #line 10 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
                
                #line default
                #line hidden
            }
            
            #line 10 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl.Href = "Content/Site.css";
            
            #line default
            #line hidden
            
            #line 10 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        303,
                        49,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control8() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
        <style>
            .qr-wrapper {
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                min-height: 100vh;
                display: flex;
                align-items: center;
                justify-content: center;
            }

            .qr-id-box {
                background: #f8f9fa;
                padding: 10px;
                border-radius: 8px;
                font-weight: 600;
                color: #555;
                word-break: break-all;
                margin-bottom: 20px;
            }
        </style>
    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        352,
                        604,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl1;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl2;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl2 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl3;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl3 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl4;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl4 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        169,
                        794,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control9() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n    <body>\r\n        ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        963,
                        24,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control10() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
            <div class=""qr-wrapper"">
                <div class=""card-premium"" style=""width: 100%; max-width: 400px; text-align: center;"">
                    <h2 style=""color: var(--primary-color); font-weight: 700;"">Scan to Pay</h2>

                    <img src=""https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=upi://pay?pa=shivshankargupta4280-1@okicici&pn=Shivshankar%20Gupta""
                        alt=""My QR Code"" style=""width: 250px; height: 250px; margin: 20px 0; border-radius: 10px;"" />

                    <div class=""qr-id-box"">
                        UPI ID: shivshankargupta4280-1@okicici
                    </div>

                    <div class=""form-group"">
                        ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1019,
                        733,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtAmount() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.TextBox)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.TextBox))));
            }
            else {
                
                #line 46 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
                @__ctrl = new global::System.Web.UI.WebControls.TextBox();
                
                #line default
                #line hidden
            }
            this.txtAmount = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 46 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl.ID = "txtAmount";
            
            #line default
            #line hidden
            
            #line 46 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Enter Amount");
            
            #line default
            #line hidden
            
            #line 46 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Number;
            
            #line default
            #line hidden
            
            #line 46 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl.CssClass = "form-control-custom";
            
            #line default
            #line hidden
            
            #line 46 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "text-align: center;");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1752,
                        190,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control11() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                    </div>\r\n\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1942,
                        52,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnSimulate() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.Button)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.Button))));
            }
            else {
                
                #line 50 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
                @__ctrl = new global::System.Web.UI.WebControls.Button();
                
                #line default
                #line hidden
            }
            this.btnSimulate = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 50 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl.ID = "btnSimulate";
            
            #line default
            #line hidden
            
            #line 50 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl.Text = "Pay & Receive Money";
            
            #line default
            #line hidden
            
            #line 50 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl.CssClass = "btn-custom";
            
            #line default
            #line hidden
            
            #line 50 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "width: 100%; margin-bottom: 15px;");
            
            #line default
            #line hidden
            
            #line 50 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl.Click -= new System.EventHandler(this.btnSimulate_Click);
            
            #line default
            #line hidden
            
            #line 50 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl.Click += new System.EventHandler(this.btnSimulate_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1994,
                        190,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control12() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n                    <a href=\"Dashboard.aspx\" style=\"color: var(--secondary-co" +
                    "lor); font-weight: 600;\">â† Back to\r\n                        Dashboard</a>\r\n   " +
                    "             </div>\r\n            </div>\r\n        ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2184,
                        210,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlForm)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlForm))));
            }
            else {
                
                #line 33 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
                
                #line default
                #line hidden
            }
            this.form1 = @__ctrl;
            
            #line 33 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 33 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl1 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 33 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            
            #line 33 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl2 = this.@__BuildControltxtAmount();
            
            #line default
            #line hidden
            
            #line 33 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 33 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl3 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 33 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl4;
            
            #line 33 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl4 = this.@__BuildControlbtnSimulate();
            
            #line default
            #line hidden
            
            #line 33 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 33 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl5 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 33 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        987,
                        1414,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control13() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    </body>\r\n\r\n    </html>");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2401,
                        28,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(myqr_aspx @__ctrl) {
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl2;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl2 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl3 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl4;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl4 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__ctrl5 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\MyQR.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.myqr_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.myqr_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 1137544644;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
