#pragma checksum "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx" "{8829d00f-11b8-4213-878b-770e8597ac16}" "4ED119881445B674C1DDFDF24DB5E6432F117DC4F086121A37F51A75B9141A06"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 415 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 13 "D:\Project\OnlineBankingTransactionSystem\web.config"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 415 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 415 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 415 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 415 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class addmoney_aspx : global::OnlineBankingTransactionSystem.AddMoney, System.Web.SessionState.IRequiresSessionState, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.addmoney_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static System.Reflection.MethodInfo @__PageInspector_BeginRenderTracingMethod = global::ASP.addmoney_aspx.@__PageInspector_LoadHelper("BeginRenderTracing");
        
        private static System.Reflection.MethodInfo @__PageInspector_EndRenderTracingMethod = global::ASP.addmoney_aspx.@__PageInspector_LoadHelper("EndRenderTracing");
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public addmoney_aspx() {
            string[] dependencies;
            ((global::OnlineBankingTransactionSystem.AddMoney)(this)).AppRelativeVirtualPath = "~/AddMoney.aspx";
            if ((global::ASP.addmoney_aspx.@__initialized == false)) {
                global::ASP.addmoney_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[1];
                dependencies[0] = "~/AddMoney.aspx";
                global::ASP.addmoney_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.addmoney_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(this.Context.ApplicationInstance));
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n    <!DOCTYPE html>\r\n    <html>\r\n\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        134,
                        43,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.WebTools.BrowserLink.Runtime.WebForms.TraceHelpers, Microsoft.WebTools." +
                    "BrowserLink.Tracing, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f1" +
                    "1d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.addmoney_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.addmoney_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        private void @__PageInspector_BeginRenderTracing(object[] parameters) {
            if ((global::ASP.addmoney_aspx.@__PageInspector_BeginRenderTracingMethod != null)) {
                global::ASP.addmoney_aspx.@__PageInspector_BeginRenderTracingMethod.Invoke(null, parameters);
            }
        }
        
        private void @__PageInspector_EndRenderTracing(object[] parameters) {
            if ((global::ASP.addmoney_aspx.@__PageInspector_EndRenderTracingMethod != null)) {
                global::ASP.addmoney_aspx.@__PageInspector_EndRenderTracingMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlMeta)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlMeta))));
            }
            else {
                
                #line 8 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
                
                #line default
                #line hidden
            }
            
            #line 8 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("charset", "UTF-8");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        208,
                        24,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control5() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlMeta)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlMeta))));
            }
            else {
                
                #line 9 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
                
                #line default
                #line hidden
            }
            
            #line 9 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl.Name = "viewport";
            
            #line default
            #line hidden
            
            #line 9 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl.Content = "width=device-width, initial-scale=1.0";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        242,
                        72,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control7() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("Add Money - Online Banking");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        331,
                        26,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control6() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlTitle)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlTitle))));
            }
            else {
                
                #line 10 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
                
                #line default
                #line hidden
            }
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 10 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl1 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 10 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        324,
                        41,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control8() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlLink)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlLink))));
            }
            else {
                
                #line 13 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
                
                #line default
                #line hidden
            }
            
            #line 13 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "preconnect");
            
            #line default
            #line hidden
            
            #line 13 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl.Href = "https://fonts.googleapis.com";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        408,
                        61,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control9() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlLink)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlLink))));
            }
            else {
                
                #line 14 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
                
                #line default
                #line hidden
            }
            
            #line 14 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "preconnect");
            
            #line default
            #line hidden
            
            #line 14 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl.Href = "https://fonts.gstatic.com";
            
            #line default
            #line hidden
            
            #line 14 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("crossorigin", "");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        479,
                        70,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control10() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlLink)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlLink))));
            }
            else {
                
                #line 15 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
                
                #line default
                #line hidden
            }
            
            #line 15 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl.Href = "https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;8" +
                "00;900&display=swap";
            
            #line default
            #line hidden
            
            #line 15 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        559,
                        159,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl1;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl2;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl2 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl3;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl3 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl4;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl4 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl5;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl5 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl6;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl6 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control3));
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        177,
                        21,
                        false});
            return @__ctrl;
        }
        
        private void @__Render__control3(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            parameterContainer.Controls[0].RenderControl(@__w);
            parameterContainer.Controls[1].RenderControl(@__w);
            parameterContainer.Controls[2].RenderControl(@__w);
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/AddMoney.aspx",
                        365,
                        43,
                        true});
            @__w.Write("\r\n\r\n        <!-- Google Fonts -->\r\n        ");
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            parameterContainer.Controls[3].RenderControl(@__w);
            parameterContainer.Controls[4].RenderControl(@__w);
            parameterContainer.Controls[5].RenderControl(@__w);
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/AddMoney.aspx",
                        718,
                        9430,
                        true});
            this.WriteUTF8ResourceString(@__w, 0, 9430, true);
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/AddMoney.aspx",
                        10148,
                        25,
                        false});
            
            #line 332 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
                                 @__w.Write( txtAmount.ClientID );

            
            #line default
            #line hidden
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/AddMoney.aspx",
                        10173,
                        55,
                        true});
            @__w.Write("\').value = amt;\r\n            }\r\n        </script>\r\n    ");
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/AddMoney.aspx",
                        10228,
                        7,
                        false});
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control11() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n    <body>\r\n        ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        10235,
                        24,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control13() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n            <div class=\"dashboard-wrapper\">\r\n                <!-- Sidebar -->\r\n" +
                    "                <aside class=\"sidebar\">\r\n                    <div class=\"sidebar" +
                    "-header\">\r\n                        <div class=\"brand\">\r\n                        " +
                    "    <div class=\"brand-icon\">\r\n                                <iconify-icon icon" +
                    "=\"lucide:landmark\" style=\"font-size: 20px\"></iconify-icon>\r\n                    " +
                    "        </div>\r\n                            NeoBank\r\n                        </d" +
                    "iv>\r\n                    </div>\r\n\r\n                    <nav class=\"nav-menu\">\r\n " +
                    "                       <a href=\"Dashboard.aspx\" class=\"nav-item\">\r\n             " +
                    "               <iconify-icon icon=\"lucide:layout-dashboard\" style=\"font-size: 20" +
                    "px\"></iconify-icon>\r\n                            Dashboard\r\n                    " +
                    "    </a>\r\n                        <a href=\"BillPayment.aspx\" class=\"nav-item\">\r\n" +
                    "                            <iconify-icon icon=\"lucide:file-text\" style=\"font-si" +
                    "ze: 20px\"></iconify-icon>\r\n                            Bill Payments\r\n          " +
                    "              </a>\r\n                        <a href=\"BillPayment.aspx\" class=\"na" +
                    "v-item\">\r\n                            <iconify-icon icon=\"lucide:smartphone\" sty" +
                    "le=\"font-size: 20px\"></iconify-icon>\r\n                            Mobile / DTH\r\n" +
                    "                        </a>\r\n                        <a href=\"SendMoney.aspx\" c" +
                    "lass=\"nav-item\">\r\n                            <iconify-icon icon=\"lucide:send\" s" +
                    "tyle=\"font-size: 20px\"></iconify-icon>\r\n                            Send Money\r\n" +
                    "                        </a>\r\n                        <a href=\"AddMoney.aspx\" cl" +
                    "ass=\"nav-item active\">\r\n                            <iconify-icon icon=\"lucide:p" +
                    "lus-circle\" style=\"font-size: 20px\"></iconify-icon>\r\n                           " +
                    " Add Money\r\n                        </a>\r\n                        <a href=\"Trans" +
                    "actionHistory.aspx\" class=\"nav-item\">\r\n                            <iconify-icon" +
                    " icon=\"lucide:history\" style=\"font-size: 20px\"></iconify-icon>\r\n                " +
                    "            Transactions\r\n                        </a>\r\n                    </na" +
                    "v>\r\n                </aside>\r\n\r\n                <!-- Main Content -->\r\n         " +
                    "       <main class=\"main-content\">\r\n                    <!-- Header -->\r\n       " +
                    "             <header class=\"top-bar\">\r\n                        <div class=\"page-" +
                    "title\">Add Money</div>\r\n                        <div class=\"top-actions\">\r\n     " +
                    "                       <a href=\"Dashboard.aspx\" class=\"back-btn\">\r\n             " +
                    "                   <iconify-icon icon=\"lucide:arrow-left\" style=\"font-size: 16px" +
                    "\"></iconify-icon>\r\n                                Back to Dashboard\r\n          " +
                    "                  </a>\r\n                        </div>\r\n                    </he" +
                    "ader>\r\n\r\n                    <!-- Body -->\r\n                    <div class=\"page" +
                    "-scroll\">\r\n                        <div class=\"page-container\">\r\n               " +
                    "             <div class=\"form-card\">\r\n                                <div class" +
                    "=\"form-header\">\r\n                                    <div class=\"form-icon\">\r\n  " +
                    "                                      <iconify-icon icon=\"lucide:wallet\" style=\"" +
                    "font-size: 32px\"></iconify-icon>\r\n                                    </div>\r\n  " +
                    "                                  <div class=\"form-title\">Add Money</div>\r\n     " +
                    "                               <div class=\"form-subtitle\">Top up your wallet ins" +
                    "tantly</div>\r\n                                </div>\r\n\r\n                        " +
                    "        <!-- Quick Amount Selection -->\r\n                                <div cl" +
                    "ass=\"quick-amounts\">\r\n                                    <button type=\"button\" " +
                    "class=\"amount-btn\" onclick=\"setAmount(500)\">₹500</button>\r\n                     " +
                    "               <button type=\"button\" class=\"amount-btn\" onclick=\"setAmount(1000)" +
                    "\">₹1,000</button>\r\n                                    <button type=\"button\" cla" +
                    "ss=\"amount-btn\" onclick=\"setAmount(2000)\">₹2,000</button>\r\n                     " +
                    "               <button type=\"button\" class=\"amount-btn\" onclick=\"setAmount(5000)" +
                    "\">₹5,000</button>\r\n                                </div>\r\n\r\n                   " +
                    "             <!-- Bank Selection -->\r\n                                <div class" +
                    "=\"form-group\">\r\n                                    <label class=\"form-label\">Se" +
                    "lect Bank Account</label>\r\n                                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        10280,
                        4304,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlBanks() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.DropDownList)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.DropDownList))));
            }
            else {
                
                #line 415 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
                @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
                
                #line default
                #line hidden
            }
            this.ddlBanks = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 415 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl.ID = "ddlBanks";
            
            #line default
            #line hidden
            
            #line 415 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl.CssClass = "form-input";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        14584,
                        126,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control14() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                                    <div style=""margin-top: 8px;"">
                                        <a href=""LinkBankAccount.aspx""
                                            style=""color: #4f46e5; text-decoration: none; font-size: 14px; font-weight: 500;"">
                                            + Link New Bank Account
                                        </a>
                                    </div>
                                </div>

                                <!-- Amount Input -->
                                <div class=""form-group"">
                                    <label class=""form-label"">Enter Amount</label>
                                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        14710,
                        704,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtAmount() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.TextBox)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.TextBox))));
            }
            else {
                
                #line 428 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
                @__ctrl = new global::System.Web.UI.WebControls.TextBox();
                
                #line default
                #line hidden
            }
            this.txtAmount = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 428 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl.ID = "txtAmount";
            
            #line default
            #line hidden
            
            #line 428 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl.CssClass = "form-input";
            
            #line default
            #line hidden
            
            #line 428 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Enter amount in ₹");
            
            #line default
            #line hidden
            
            #line 428 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Number;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        15414,
                        170,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control15() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                </div>\r\n\r\n                                <!-- " +
                    "Submit Button -->\r\n                                ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        15584,
                        132,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnAdd() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.Button)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.Button))));
            }
            else {
                
                #line 433 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
                @__ctrl = new global::System.Web.UI.WebControls.Button();
                
                #line default
                #line hidden
            }
            this.btnAdd = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 433 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl.ID = "btnAdd";
            
            #line default
            #line hidden
            
            #line 433 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl.Text = "Add Money";
            
            #line default
            #line hidden
            
            #line 433 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl.CssClass = "btn-primary";
            
            #line default
            #line hidden
            
            #line 433 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl.Click -= new System.EventHandler(this.AddButton_Click);
            
            #line default
            #line hidden
            
            #line 433 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl.Click += new System.EventHandler(this.AddButton_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        15716,
                        144,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control16() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                            </div>\r\n                        </div>\r\n           " +
                    "         </div>\r\n                </main>\r\n            </div>\r\n        ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        15860,
                        151,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControl__control12() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlForm)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlForm))));
            }
            else {
                
                #line 338 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
                
                #line default
                #line hidden
            }
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 338 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl1 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 338 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl2;
            
            #line 338 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl2 = this.@__BuildControlddlBanks();
            
            #line default
            #line hidden
            
            #line 338 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 338 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl3 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 338 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            
            #line 338 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl4 = this.@__BuildControltxtAmount();
            
            #line default
            #line hidden
            
            #line 338 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 338 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl5 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            
            #line 338 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl6;
            
            #line 338 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl6 = this.@__BuildControlbtnAdd();
            
            #line default
            #line hidden
            
            #line 338 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 338 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl7 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            
            #line 338 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        10259,
                        5759,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control17() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    </body>\r\n\r\n    </html>");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        16018,
                        28,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(addmoney_aspx @__ctrl) {
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl2;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl2 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl3 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl4;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl4 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__ctrl5 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AddMoney.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.addmoney_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.addmoney_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 1564259058;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
