#pragma checksum "D:\Project\OnlineBankingTransactionSystem\About.aspx" "{8829d00f-11b8-4213-878b-770e8597ac16}" "57443088C436376EB0E8F37B0DBC0E01ABD20C4ABB1DACFA037EC5BA80942B3F"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 3 "D:\Project\OnlineBankingTransactionSystem\About.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 13 "D:\Project\OnlineBankingTransactionSystem\web.config"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 3 "D:\Project\OnlineBankingTransactionSystem\About.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "D:\Project\OnlineBankingTransactionSystem\About.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 3 "D:\Project\OnlineBankingTransactionSystem\About.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 3 "D:\Project\OnlineBankingTransactionSystem\About.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "D:\Project\OnlineBankingTransactionSystem\About.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class about_aspx : global::OnlineBankingTransactionSystem.About, System.Web.SessionState.IRequiresSessionState, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_BeginRenderTracingMethod = global::ASP.about_aspx.@__PageInspector_LoadHelper("BeginRenderTracing");
        
        private static System.Reflection.MethodInfo @__PageInspector_EndRenderTracingMethod = global::ASP.about_aspx.@__PageInspector_LoadHelper("EndRenderTracing");
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public about_aspx() {
            string[] dependencies;
            ((global::OnlineBankingTransactionSystem.About)(this)).AppRelativeVirtualPath = "~/About.aspx";
            if ((global::ASP.about_aspx.@__initialized == false)) {
                global::ASP.about_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[2];
                dependencies[0] = "~/About.aspx";
                dependencies[1] = "~/Site.Master";
                global::ASP.about_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.about_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(this.Context.ApplicationInstance));
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlBodyContent(System.Web.UI.Control @__ctrl) {
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderBodyContent));
        }
        
        private void @__RenderBodyContent(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/About.aspx",
                        252,
                        61,
                        true});
            @__w.Write("\r\n    <main aria-labelledby=\"title\">\r\n        <h2 id=\"title\">");
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/About.aspx",
                        313,
                        12,
                        false});
            
            #line 5 "D:\Project\OnlineBankingTransactionSystem\About.aspx"
@__w.Write(System.Web.HttpUtility.HtmlEncode( Title ));

            
            #line default
            #line hidden
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/About.aspx",
                        325,
                        139,
                        true});
            @__w.Write(".</h2>\r\n        <h3>Your application description page.</h3>\r\n        <p>Use this " +
                    "area to provide additional information.</p>\r\n    </main>\r\n");
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.WebTools.BrowserLink.Runtime.WebForms.TraceHelpers, Microsoft.WebTools." +
                    "BrowserLink.Tracing, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f1" +
                    "1d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_BeginRenderTracing(object[] parameters) {
            if ((global::ASP.about_aspx.@__PageInspector_BeginRenderTracingMethod != null)) {
                global::ASP.about_aspx.@__PageInspector_BeginRenderTracingMethod.Invoke(null, parameters);
            }
        }
        
        private void @__PageInspector_EndRenderTracing(object[] parameters) {
            if ((global::ASP.about_aspx.@__PageInspector_EndRenderTracingMethod != null)) {
                global::ASP.about_aspx.@__PageInspector_EndRenderTracingMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(about_aspx @__ctrl) {
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\About.aspx"
            @__ctrl.Title = "About";
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\About.aspx"
            @__ctrl.MasterPageFile = "~/Site.Master";
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\About.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 3 "D:\Project\OnlineBankingTransactionSystem\About.aspx"
            this.AddContentTemplate("MainContent", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlBodyContent)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\About.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.about_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.about_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 253599918;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
