#pragma checksum "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx" "{8829d00f-11b8-4213-878b-770e8597ac16}" "7921D1272DF82F192E0843F3580ABB9ABF827B76A035CA234EF2B4202A31A6F4"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 13 "D:\Project\OnlineBankingTransactionSystem\web.config"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class adminkyc_aspx : global::OnlineBankingTransactionSystem.AdminKYC, System.Web.SessionState.IRequiresSessionState, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.adminkyc_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public adminkyc_aspx() {
            string[] dependencies;
            ((global::OnlineBankingTransactionSystem.AdminKYC)(this)).AppRelativeVirtualPath = "~/AdminKYC.aspx";
            if ((global::ASP.adminkyc_aspx.@__initialized == false)) {
                global::ASP.adminkyc_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[1];
                dependencies[0] = "~/AdminKYC.aspx";
                global::ASP.adminkyc_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.adminkyc_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(this.Context.ApplicationInstance));
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n    <!DOCTYPE html>\r\n    <html lang=\"en\">\r\n\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        134,
                        53,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.WebTools.BrowserLink.Runtime.WebForms.TraceHelpers, Microsoft.WebTools." +
                    "BrowserLink.Tracing, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f1" +
                    "1d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.adminkyc_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.adminkyc_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlMeta)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlMeta))));
            }
            else {
                
                #line 8 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
                
                #line default
                #line hidden
            }
            
            #line 8 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("charset", "UTF-8");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        218,
                        24,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control5() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlMeta)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlMeta))));
            }
            else {
                
                #line 9 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
                
                #line default
                #line hidden
            }
            
            #line 9 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.Name = "viewport";
            
            #line default
            #line hidden
            
            #line 9 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.Content = "width=device-width, initial-scale=1.0";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        252,
                        72,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control7() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("KYC Requests — NeoBank Admin");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        341,
                        28,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control6() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlTitle)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlTitle))));
            }
            else {
                
                #line 10 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
                
                #line default
                #line hidden
            }
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 10 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl1 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 10 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        334,
                        43,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control8() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlLink)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlLink))));
            }
            else {
                
                #line 11 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
                
                #line default
                #line hidden
            }
            
            #line 11 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "preconnect");
            
            #line default
            #line hidden
            
            #line 11 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.Href = "https://fonts.googleapis.com";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        387,
                        61,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control9() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlLink)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlLink))));
            }
            else {
                
                #line 12 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
                
                #line default
                #line hidden
            }
            
            #line 12 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "preconnect");
            
            #line default
            #line hidden
            
            #line 12 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.Href = "https://fonts.gstatic.com";
            
            #line default
            #line hidden
            
            #line 12 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("crossorigin", "crossorigin");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        458,
                        84,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control10() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlLink)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlLink))));
            }
            else {
                
                #line 13 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
                
                #line default
                #line hidden
            }
            
            #line 13 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.Href = "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&displ" +
                "ay=swap";
            
            #line default
            #line hidden
            
            #line 13 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        552,
                        134,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control11() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n        <script src=\"https://code.iconify.design/iconify-icon/3.0.0/iconify-ico" +
                    "n.min.js\"></script>\r\n        <style>\r\n            :root {\r\n                --bg:" +
                    " #0d1117;\r\n                --sidebar: #010409;\r\n                --card: #161b22;" +
                    "\r\n                --card2: #1c2128;\r\n                --border: rgba(255, 255, 25" +
                    "5, .08);\r\n                --primary: #7c3aed;\r\n                --primary2: #6366" +
                    "f1;\r\n                --success: #10b981;\r\n                --warning: #f59e0b;\r\n " +
                    "               --danger: #ef4444;\r\n                --text: #e6edf3;\r\n           " +
                    "     --muted: #7d8590;\r\n                --radius: 12px;\r\n            }\r\n\r\n      " +
                    "      *,\r\n            *::before,\r\n            *::after {\r\n                box-si" +
                    "zing: border-box;\r\n                margin: 0;\r\n                padding: 0;\r\n    " +
                    "        }\r\n\r\n            body {\r\n                font-family: \'Inter\', sans-seri" +
                    "f;\r\n                background: var(--bg);\r\n                color: var(--text);\r" +
                    "\n                display: flex;\r\n                height: 100vh;\r\n               " +
                    " overflow: hidden;\r\n            }\r\n\r\n            /* Sidebar */\r\n            .sid" +
                    "ebar {\r\n                width: 240px;\r\n                flex-shrink: 0;\r\n        " +
                    "        background: var(--sidebar);\r\n                border-right: 1px solid var" +
                    "(--border);\r\n                display: flex;\r\n                flex-direction: col" +
                    "umn;\r\n                height: 100vh;\r\n                overflow-y: auto;\r\n       " +
                    "     }\r\n\r\n            .sb-logo {\r\n                padding: 24px 20px 20px;\r\n    " +
                    "            display: flex;\r\n                align-items: center;\r\n              " +
                    "  gap: 10px;\r\n                border-bottom: 1px solid var(--border);\r\n         " +
                    "   }\r\n\r\n            .sb-logo-icon {\r\n                width: 36px;\r\n             " +
                    "   height: 36px;\r\n                border-radius: 10px;\r\n                backgrou" +
                    "nd: linear-gradient(135deg, var(--primary), var(--primary2));\r\n                d" +
                    "isplay: flex;\r\n                align-items: center;\r\n                justify-con" +
                    "tent: center;\r\n                box-shadow: 0 4px 12px rgba(124, 58, 237, .4);\r\n " +
                    "           }\r\n\r\n            .sb-logo-text {\r\n                font-size: 17px;\r\n " +
                    "               font-weight: 800;\r\n                color: var(--text);\r\n         " +
                    "   }\r\n\r\n            .sb-badge {\r\n                font-size: 9px;\r\n              " +
                    "  font-weight: 700;\r\n                background: var(--primary);\r\n              " +
                    "  color: white;\r\n                padding: 2px 7px;\r\n                border-radiu" +
                    "s: 100px;\r\n                margin-left: 6px;\r\n                letter-spacing: .0" +
                    "5em;\r\n                text-transform: uppercase;\r\n            }\r\n\r\n            ." +
                    "sb-section {\r\n                padding: 20px 12px 8px;\r\n                font-size" +
                    ": 11px;\r\n                font-weight: 600;\r\n                color: var(--muted);" +
                    "\r\n                letter-spacing: .08em;\r\n                text-transform: upperc" +
                    "ase;\r\n            }\r\n\r\n            .sb-item {\r\n                display: flex;\r\n " +
                    "               align-items: center;\r\n                gap: 10px;\r\n               " +
                    " padding: 10px 16px;\r\n                border-radius: 9px;\r\n                margi" +
                    "n: 2px 8px;\r\n                font-size: 14px;\r\n                font-weight: 500;" +
                    "\r\n                color: var(--muted);\r\n                text-decoration: none;\r\n" +
                    "                transition: all .15s;\r\n            }\r\n\r\n            .sb-item:hov" +
                    "er {\r\n                background: rgba(255, 255, 255, .06);\r\n                col" +
                    "or: var(--text);\r\n            }\r\n\r\n            .sb-item.active {\r\n              " +
                    "  background: rgba(124, 58, 237, .18);\r\n                color: #a78bfa;\r\n       " +
                    "     }\r\n\r\n            .sb-spacer {\r\n                flex: 1;\r\n            }\r\n\r\n " +
                    "           .sb-user {\r\n                padding: 16px 20px;\r\n                bord" +
                    "er-top: 1px solid var(--border);\r\n                display: flex;\r\n              " +
                    "  align-items: center;\r\n                gap: 10px;\r\n            }\r\n\r\n           " +
                    " .sb-avatar {\r\n                width: 34px;\r\n                height: 34px;\r\n    " +
                    "            border-radius: 50%;\r\n                background: linear-gradient(135" +
                    "deg, var(--primary), var(--primary2));\r\n                display: flex;\r\n        " +
                    "        align-items: center;\r\n                justify-content: center;\r\n        " +
                    "        font-size: 13px;\r\n                font-weight: 700;\r\n                col" +
                    "or: white;\r\n                flex-shrink: 0;\r\n            }\r\n\r\n            .sb-us" +
                    "er-name {\r\n                font-size: 13px;\r\n                font-weight: 600;\r\n" +
                    "                color: var(--text);\r\n            }\r\n\r\n            .sb-user-role " +
                    "{\r\n                font-size: 11px;\r\n                color: var(--muted);\r\n     " +
                    "       }\r\n\r\n            /* Main */\r\n            .main {\r\n                flex: 1" +
                    ";\r\n                display: flex;\r\n                flex-direction: column;\r\n    " +
                    "            overflow: hidden;\r\n            }\r\n\r\n            .topbar {\r\n         " +
                    "       height: 62px;\r\n                background: var(--card);\r\n                " +
                    "border-bottom: 1px solid var(--border);\r\n                display: flex;\r\n       " +
                    "         align-items: center;\r\n                justify-content: space-between;\r\n" +
                    "                padding: 0 28px;\r\n                flex-shrink: 0;\r\n            }" +
                    "\r\n\r\n            .topbar-title {\r\n                font-size: 17px;\r\n             " +
                    "   font-weight: 700;\r\n                color: var(--text);\r\n                displ" +
                    "ay: flex;\r\n                align-items: center;\r\n                gap: 10px;\r\n   " +
                    "         }\r\n\r\n            .topbar-right {\r\n                display: flex;\r\n     " +
                    "           align-items: center;\r\n                gap: 12px;\r\n            }\r\n\r\n  " +
                    "          .pending-count {\r\n                background: rgba(245, 158, 11, .15);" +
                    "\r\n                border: 1px solid rgba(245, 158, 11, .3);\r\n                col" +
                    "or: #fbbf24;\r\n                font-size: 12px;\r\n                font-weight: 700" +
                    ";\r\n                padding: 4px 14px;\r\n                border-radius: 100px;\r\n  " +
                    "          }\r\n\r\n            .btn-back {\r\n                background: rgba(255, 25" +
                    "5, 255, .07);\r\n                border: 1px solid var(--border);\r\n               " +
                    " color: var(--muted);\r\n                padding: 8px 14px;\r\n                borde" +
                    "r-radius: 9px;\r\n                font-size: 13px;\r\n                font-weight: 5" +
                    "00;\r\n                font-family: \'Inter\', sans-serif;\r\n                cursor: " +
                    "pointer;\r\n                text-decoration: none;\r\n                display: flex;" +
                    "\r\n                align-items: center;\r\n                gap: 7px;\r\n             " +
                    "   transition: all .15s;\r\n            }\r\n\r\n            .btn-back:hover {\r\n      " +
                    "          background: rgba(255, 255, 255, .12);\r\n                color: var(--te" +
                    "xt);\r\n            }\r\n\r\n            .main-body {\r\n                flex: 1;\r\n     " +
                    "           overflow-y: auto;\r\n                padding: 28px;\r\n            }\r\n\r\n " +
                    "           /* Filter bar */\r\n            .filter-bar {\r\n                backgrou" +
                    "nd: var(--card);\r\n                border: 1px solid var(--border);\r\n            " +
                    "    border-radius: var(--radius);\r\n                padding: 16px 22px;\r\n        " +
                    "        margin-bottom: 20px;\r\n                display: flex;\r\n                al" +
                    "ign-items: center;\r\n                gap: 12px;\r\n            }\r\n\r\n            .fi" +
                    "lter-label {\r\n                font-size: 13px;\r\n                font-weight: 600" +
                    ";\r\n                color: var(--muted);\r\n            }\r\n\r\n            .filter-ch" +
                    "ip {\r\n                padding: 7px 14px;\r\n                border-radius: 8px;\r\n " +
                    "               border: 1px solid var(--border);\r\n                background: tra" +
                    "nsparent;\r\n                color: var(--muted);\r\n                font-size: 12px" +
                    ";\r\n                font-weight: 600;\r\n                font-family: \'Inter\', sans" +
                    "-serif;\r\n                cursor: pointer;\r\n                transition: all .15s;" +
                    "\r\n            }\r\n\r\n            .filter-chip.active,\r\n            .filter-chip:ho" +
                    "ver {\r\n                background: rgba(124, 58, 237, .18);\r\n                bor" +
                    "der-color: rgba(124, 58, 237, .4);\r\n                color: #a78bfa;\r\n           " +
                    " }\r\n\r\n            /* Table */\r\n            .table-card {\r\n                backgr" +
                    "ound: var(--card);\r\n                border: 1px solid var(--border);\r\n          " +
                    "      border-radius: var(--radius);\r\n                overflow: hidden;\r\n        " +
                    "    }\r\n\r\n            .table-header {\r\n                padding: 18px 24px;\r\n     " +
                    "           border-bottom: 1px solid var(--border);\r\n                display: fle" +
                    "x;\r\n                align-items: center;\r\n                justify-content: space" +
                    "-between;\r\n            }\r\n\r\n            .table-title {\r\n                font-siz" +
                    "e: 15px;\r\n                font-weight: 700;\r\n                color: var(--text);" +
                    "\r\n                display: flex;\r\n                align-items: center;\r\n        " +
                    "        gap: 8px;\r\n            }\r\n\r\n            .table-desc {\r\n                f" +
                    "ont-size: 13px;\r\n                color: var(--muted);\r\n                margin-to" +
                    "p: 3px;\r\n            }\r\n\r\n            .admin-grid {\r\n                width: 100%" +
                    ";\r\n                border-collapse: collapse;\r\n            }\r\n\r\n            .adm" +
                    "in-grid th {\r\n                background: var(--card2);\r\n                color: " +
                    "var(--muted);\r\n                font-size: 11px;\r\n                font-weight: 60" +
                    "0;\r\n                text-transform: uppercase;\r\n                letter-spacing: " +
                    ".07em;\r\n                padding: 12px 20px;\r\n                text-align: left;\r\n" +
                    "                border-bottom: 1px solid var(--border);\r\n            }\r\n\r\n      " +
                    "      .admin-grid td {\r\n                padding: 15px 20px;\r\n                bor" +
                    "der-bottom: 1px solid rgba(255, 255, 255, .04);\r\n                font-size: 13px" +
                    ";\r\n                color: var(--text);\r\n                vertical-align: middle;\r" +
                    "\n            }\r\n\r\n            .admin-grid tr:last-child td {\r\n                bo" +
                    "rder-bottom: none;\r\n            }\r\n\r\n            .admin-grid tr:hover td {\r\n    " +
                    "            background: rgba(255, 255, 255, .025);\r\n            }\r\n\r\n           " +
                    " .kyc-status {\r\n                display: inline-flex;\r\n                align-ite" +
                    "ms: center;\r\n                gap: 5px;\r\n                padding: 4px 12px;\r\n    " +
                    "            border-radius: 100px;\r\n                font-size: 11px;\r\n           " +
                    "     font-weight: 700;\r\n                text-transform: uppercase;\r\n            " +
                    "    letter-spacing: .05em;\r\n            }\r\n\r\n            .kyc-status.pending {\r\n" +
                    "                background: rgba(245, 158, 11, .15);\r\n                border: 1p" +
                    "x solid rgba(245, 158, 11, .3);\r\n                color: #fbbf24;\r\n            }\r" +
                    "\n\r\n            .kyc-status.verified {\r\n                background: rgba(16, 185," +
                    " 129, .15);\r\n                border: 1px solid rgba(16, 185, 129, .3);\r\n        " +
                    "        color: #34d399;\r\n            }\r\n\r\n            .kyc-status.rejected {\r\n  " +
                    "              background: rgba(239, 68, 68, .15);\r\n                border: 1px s" +
                    "olid rgba(239, 68, 68, .3);\r\n                color: #f87171;\r\n            }\r\n\r\n " +
                    "           .btn-approve {\r\n                background: rgba(16, 185, 129, .15);\r" +
                    "\n                border: 1px solid rgba(16, 185, 129, .3);\r\n                colo" +
                    "r: #34d399;\r\n                padding: 7px 16px;\r\n                border-radius: " +
                    "8px;\r\n                font-size: 12px;\r\n                font-weight: 700;\r\n     " +
                    "           font-family: \'Inter\', sans-serif;\r\n                cursor: pointer;\r\n" +
                    "                transition: all .15s;\r\n                margin-right: 6px;\r\n     " +
                    "       }\r\n\r\n            .btn-approve:hover {\r\n                background: rgba(1" +
                    "6, 185, 129, .3);\r\n            }\r\n\r\n            .btn-reject {\r\n                b" +
                    "ackground: rgba(239, 68, 68, .1);\r\n                border: 1px solid rgba(239, 6" +
                    "8, 68, .25);\r\n                color: #f87171;\r\n                padding: 7px 16px" +
                    ";\r\n                border-radius: 8px;\r\n                font-size: 12px;\r\n      " +
                    "          font-weight: 700;\r\n                font-family: \'Inter\', sans-serif;\r\n" +
                    "                cursor: pointer;\r\n                transition: all .15s;\r\n       " +
                    "     }\r\n\r\n            .btn-reject:hover {\r\n                background: rgba(239," +
                    " 68, 68, .25);\r\n            }\r\n\r\n            .empty-td {\r\n                text-a" +
                    "lign: center;\r\n                padding: 60px 20px !important;\r\n                c" +
                    "olor: var(--muted);\r\n            }\r\n        </style>\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        686,
                        12219,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl1;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl2;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl2 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl3;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl3 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl4;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl4 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl5;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl5 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl6;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl6 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl7 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 7 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        187,
                        12725,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control12() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n    <body>\r\n        ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        12912,
                        24,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control14() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n            <div style=\"display:flex; height:100vh; overflow:hidden;\">\r\n\r\n     " +
                    "           <!-- Sidebar -->\r\n                <aside class=\"sidebar\">\r\n          " +
                    "          <div class=\"sb-logo\">\r\n                        <div class=\"sb-logo-ico" +
                    "n\">\r\n                            <iconify-icon icon=\"lucide:landmark\" style=\"fon" +
                    "t-size:20px; color:white\"></iconify-icon>\r\n                        </div>\r\n     " +
                    "                   <span class=\"sb-logo-text\">NeoBank <span class=\"sb-badge\">Adm" +
                    "in</span></span>\r\n                    </div>\r\n                    <div class=\"sb" +
                    "-section\">Navigation</div>\r\n                    <a href=\"AdminDashboard.aspx\" cl" +
                    "ass=\"sb-item\">\r\n                        <iconify-icon icon=\"lucide:layout-dashbo" +
                    "ard\" style=\"font-size:18px\"></iconify-icon>Dashboard\r\n                    </a>\r\n" +
                    "                    <a href=\"AdminKYC.aspx\" class=\"sb-item active\">\r\n           " +
                    "             <iconify-icon icon=\"lucide:shield-check\" style=\"font-size:18px\"></i" +
                    "conify-icon>KYC Requests\r\n                    </a>\r\n                    <a href=" +
                    "\"AdminUsers.aspx\" class=\"sb-item\">\r\n                        <iconify-icon icon=\"" +
                    "lucide:users\" style=\"font-size:18px\"></iconify-icon>All Users\r\n                 " +
                    "   </a>\r\n                    <a href=\"AdminTransactions.aspx\" class=\"sb-item\">\r\n" +
                    "                        <iconify-icon icon=\"lucide:activity\" style=\"font-size:18" +
                    "px\"></iconify-icon>Transactions\r\n                    </a>\r\n                    <" +
                    "a href=\"AdminLinkedAccounts.aspx\" class=\"sb-item\">\r\n                        <ico" +
                    "nify-icon icon=\"lucide:credit-card\" style=\"font-size:18px\"></iconify-icon>Linked" +
                    " Accounts\r\n                    </a>\r\n                    <div class=\"sb-spacer\">" +
                    "</div>\r\n                    <div class=\"sb-user\">\r\n                        <div " +
                    "class=\"sb-avatar\">A</div>\r\n                        <div>\r\n                      " +
                    "      <div class=\"sb-user-name\">Administrator</div>\r\n                           " +
                    " <div class=\"sb-user-role\">Super Admin</div>\r\n                        </div>\r\n  " +
                    "                  </div>\r\n                </aside>\r\n\r\n                <!-- Main " +
                    "-->\r\n                <div class=\"main\">\r\n                    <header class=\"topb" +
                    "ar\">\r\n                        <div class=\"topbar-title\">\r\n                      " +
                    "      <iconify-icon icon=\"lucide:shield-check\"\r\n                                " +
                    "style=\"font-size:20px; color:#a78bfa\"></iconify-icon>\r\n                         " +
                    "   KYC Requests\r\n                        </div>\r\n                        <div cl" +
                    "ass=\"topbar-right\">\r\n                            <span class=\"pending-count\">⏳ P" +
                    "ending Review</span>\r\n                            <a href=\"AdminDashboard.aspx\" " +
                    "class=\"btn-back\">\r\n                                <iconify-icon icon=\"lucide:ar" +
                    "row-left\" style=\"font-size:14px\"></iconify-icon>\r\n                              " +
                    "  Back to Dashboard\r\n                            </a>\r\n                        <" +
                    "/div>\r\n                    </header>\r\n\r\n                    <div class=\"main-bod" +
                    "y\">\r\n\r\n                        <!-- Filter Bar -->\r\n                        <div" +
                    " class=\"filter-bar\">\r\n                            <span class=\"filter-label\">Sho" +
                    "w:</span>\r\n                            <button class=\"filter-chip active\" type=\"" +
                    "button\">All Requests</button>\r\n                            <button class=\"filter" +
                    "-chip\" type=\"button\">⏳ Pending</button>\r\n                            <button cla" +
                    "ss=\"filter-chip\" type=\"button\">✅ Verified</button>\r\n                            " +
                    "<button class=\"filter-chip\" type=\"button\">❌ Rejected</button>\r\n                 " +
                    "       </div>\r\n\r\n                        <!-- Table -->\r\n                       " +
                    " <div class=\"table-card\">\r\n                            <div class=\"table-header\"" +
                    ">\r\n                                <div>\r\n                                    <d" +
                    "iv class=\"table-title\">\r\n                                        <iconify-icon i" +
                    "con=\"lucide:users\"\r\n                                            style=\"font-size" +
                    ":16px; color:#a78bfa\"></iconify-icon>\r\n                                        K" +
                    "YC Verification Requests\r\n                                    </div>\r\n          " +
                    "                          <div class=\"table-desc\">Review and approve or reject e" +
                    "ach customer\'s KYC submission\r\n                                    </div>\r\n     " +
                    "                           </div>\r\n                            </div>\r\n\r\n       " +
                    "                     ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        12957,
                        4342,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control16() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                                    <table style=""width:100%"">
                                        <tr>
                                            <td class=""empty-td"" colspan=""5"">
                                                <iconify-icon icon=""lucide:check-circle-2""
                                                    style=""font-size:48px; color:#34d399; display:block; margin:0 auto 14px;""></iconify-icon>
                                                <strong
                                                    style=""color:#e6edf3; font-size:15px; display:block; margin-bottom:8px;"">All
                                                    clear!</strong>
                                                No pending KYC requests at the moment.
                                            </td>
                                        </tr>
                                    </table>
                                ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        19249,
                        946,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control15(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl1 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control18() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 499 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 499 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.DataField = "UserID";
            
            #line default
            #line hidden
            
            #line 499 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.HeaderText = "User ID";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control19() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 500 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 500 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.DataField = "AadhaarNumber";
            
            #line default
            #line hidden
            
            #line 500 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.HeaderText = "Aadhaar No.";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control20() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 501 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 501 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.DataField = "PANNumber";
            
            #line default
            #line hidden
            
            #line 501 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.HeaderText = "PAN No.";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__control23() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            
            #line 504 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(3, 2);
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.SetStaticString(0, "\r\n                                            <span class=\'kyc-status ");
            @__ctrl.SetStaticString(1, "\'>\r\n                                                ");
            @__ctrl.SetStaticString(2, "\r\n                                            </span>\r\n                          " +
                    "              ");
            
            #line 504 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__control23);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        17966,
                        191,
                        false});
            return @__ctrl;
        }
        
        public void @__DataBind__control23(object sender, System.EventArgs e) {
            System.Web.UI.IDataItemContainer Container;
            System.Web.UI.DataBoundLiteralControl target;
            
            #line 504 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            
            #line default
            #line hidden
            
            #line 504 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));
            
            #line default
            #line hidden
            
            #line 504 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            target.SetDataBoundString(0, global::System.Convert.ToString(Eval("KYCStatus").ToString().ToLower(), global::System.Globalization.CultureInfo.CurrentCulture));
            
            #line default
            #line hidden
            
            #line 505 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            target.SetDataBoundString(1, global::System.Convert.ToString(Eval("KYCStatus"), global::System.Globalization.CultureInfo.CurrentCulture));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control22(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl1;
            
            #line 502 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl1 = this.@__BuildControl__control23();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 502 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TemplateField @__BuildControl__control21() {
            global::System.Web.UI.WebControls.TemplateField @__ctrl;
            
            #line 502 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TemplateField();
            
            #line default
            #line hidden
            
            #line 502 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control22), null);
            
            #line default
            #line hidden
            
            #line 502 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.HeaderText = "KYC Status";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control26() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                            ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        18459,
                        46,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControl__control27() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.Button)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.Button))));
            }
            else {
                
                #line 511 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
                @__ctrl = new global::System.Web.UI.WebControls.Button();
                
                #line default
                #line hidden
            }
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 511 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.ID = "btnApprove";
            
            #line default
            #line hidden
            
            #line 511 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.Text = "✓ Approve";
            
            #line default
            #line hidden
            
            #line 511 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.CssClass = "btn-approve";
            
            #line default
            #line hidden
            
            #line 511 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.CommandName = "APPROVE";
            
            #line default
            #line hidden
            
            #line 511 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control27);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        18505,
                        245,
                        false});
            return @__ctrl;
        }
        
        public void @__DataBinding__control27(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.Button dataBindingExpressionBuilderTarget;
            System.Web.UI.IDataItemContainer Container;
            
            #line 511 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Button)(sender));
            
            #line default
            #line hidden
            
            #line 511 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));
            
            #line default
            #line hidden
            
            #line 511 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            dataBindingExpressionBuilderTarget.CommandArgument = global::System.Convert.ToString( Eval("UserID") , global::System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control28() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                            ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        18750,
                        46,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControl__control29() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.Button)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.Button))));
            }
            else {
                
                #line 514 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
                @__ctrl = new global::System.Web.UI.WebControls.Button();
                
                #line default
                #line hidden
            }
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 514 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.ID = "btnReject";
            
            #line default
            #line hidden
            
            #line 514 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.Text = "✕ Reject";
            
            #line default
            #line hidden
            
            #line 514 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.CssClass = "btn-reject";
            
            #line default
            #line hidden
            
            #line 514 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.CommandName = "REJECT";
            
            #line default
            #line hidden
            
            #line 514 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control29);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        18796,
                        241,
                        false});
            return @__ctrl;
        }
        
        public void @__DataBinding__control29(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.Button dataBindingExpressionBuilderTarget;
            System.Web.UI.IDataItemContainer Container;
            
            #line 514 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Button)(sender));
            
            #line default
            #line hidden
            
            #line 514 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));
            
            #line default
            #line hidden
            
            #line 514 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            dataBindingExpressionBuilderTarget.CommandArgument = global::System.Convert.ToString( Eval("UserID") , global::System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control30() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        19037,
                        42,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control25(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 509 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl1 = this.@__BuildControl__control26();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 509 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl2;
            
            #line 509 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl2 = this.@__BuildControl__control27();
            
            #line default
            #line hidden
            
            #line 509 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 509 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl3 = this.@__BuildControl__control28();
            
            #line default
            #line hidden
            
            #line 509 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl4;
            
            #line 509 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl4 = this.@__BuildControl__control29();
            
            #line default
            #line hidden
            
            #line 509 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 509 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl5 = this.@__BuildControl__control30();
            
            #line default
            #line hidden
            
            #line 509 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TemplateField @__BuildControl__control24() {
            global::System.Web.UI.WebControls.TemplateField @__ctrl;
            
            #line 509 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TemplateField();
            
            #line default
            #line hidden
            
            #line 509 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control25), null);
            
            #line default
            #line hidden
            
            #line 509 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.HeaderText = "Actions";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control17(System.Web.UI.WebControls.DataControlFieldCollection @__ctrl) {
            global::System.Web.UI.WebControls.BoundField @__ctrl1;
            
            #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl1 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            
            #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl2;
            
            #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl2 = this.@__BuildControl__control19();
            
            #line default
            #line hidden
            
            #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl3;
            
            #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl3 = this.@__BuildControl__control20();
            
            #line default
            #line hidden
            
            #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TemplateField @__ctrl4;
            
            #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl4 = this.@__BuildControl__control21();
            
            #line default
            #line hidden
            
            #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TemplateField @__ctrl5;
            
            #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl5 = this.@__BuildControl__control24();
            
            #line default
            #line hidden
            
            #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.Add(@__ctrl5);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgvKYC() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.GridView)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.GridView))));
            }
            else {
                
                #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
                @__ctrl = new global::System.Web.UI.WebControls.GridView();
                
                #line default
                #line hidden
            }
            this.gvKYC = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.EmptyDataTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control15));
            
            #line default
            #line hidden
            
            #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.ID = "gvKYC";
            
            #line default
            #line hidden
            
            #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.AutoGenerateColumns = false;
            
            #line default
            #line hidden
            
            #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.CssClass = "admin-grid";
            
            #line default
            #line hidden
            
            #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            
            #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.None;
            
            #line default
            #line hidden
            
            #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            this.@__BuildControl__control17(@__ctrl.Columns);
            
            #line default
            #line hidden
            
            #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.RowCommand -= new System.Web.UI.WebControls.GridViewCommandEventHandler(this.gvKYC_RowCommand);
            
            #line default
            #line hidden
            
            #line 496 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl.RowCommand += new System.Web.UI.WebControls.GridViewCommandEventHandler(this.gvKYC_RowCommand);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        17299,
                        2961,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control31() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                        </div>\r\n\r\n                    </div>\r\n                <" +
                    "/div>\r\n            </div>\r\n        ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        20260,
                        116,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControl__control13() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.HtmlControls.HtmlForm)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.HtmlControls.HtmlForm))));
            }
            else {
                
                #line 417 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
                @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
                
                #line default
                #line hidden
            }
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 417 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl1 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 417 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.GridView @__ctrl2;
            
            #line 417 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl2 = this.@__BuildControlgvKYC();
            
            #line default
            #line hidden
            
            #line 417 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 417 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl3 = this.@__BuildControl__control31();
            
            #line default
            #line hidden
            
            #line 417 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        12936,
                        7447,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control32() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    </body>\r\n\r\n    </html>");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        20383,
                        28,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(adminkyc_aspx @__ctrl) {
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl2;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl2 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl3 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl4;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl4 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__ctrl5 = this.@__BuildControl__control32();
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\AdminKYC.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.adminkyc_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.adminkyc_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 2043455889;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
