#pragma checksum "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx" "{8829d00f-11b8-4213-878b-770e8597ac16}" "78CC820FA0D78953D7174C645A53B34125EA906DC9D35B59F5EAD7347B519AB2"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 4 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 13 "D:\Project\OnlineBankingTransactionSystem\web.config"
    using System.Web.Optimization;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 4 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 4 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 4 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 4 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class managebeneficiaries_aspx : global::OnlineBankingTransactionSystem.ManageBeneficiaries, System.Web.SessionState.IRequiresSessionState, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.managebeneficiaries_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public managebeneficiaries_aspx() {
            string[] dependencies;
            ((global::OnlineBankingTransactionSystem.ManageBeneficiaries)(this)).AppRelativeVirtualPath = "~/ManageBeneficiaries.aspx";
            if ((global::ASP.managebeneficiaries_aspx.@__initialized == false)) {
                global::ASP.managebeneficiaries_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[2];
                dependencies[0] = "~/ManageBeneficiaries.aspx";
                dependencies[1] = "~/Main.Master";
                global::ASP.managebeneficiaries_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.managebeneficiaries_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(this.Context.ApplicationInstance));
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n        Manage Beneficiaries - Online Banking\r\n    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        302,
                        53,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.WebTools.BrowserLink.Runtime.WebForms.TraceHelpers, Microsoft.WebTools." +
                    "BrowserLink.Tracing, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f1" +
                    "1d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.managebeneficiaries_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.managebeneficiaries_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 4 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 4 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control3() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n        <style>\r\n            .page-container {\r\n                max-width: 900p" +
                    "x;\r\n                margin: 0 auto;\r\n            }\r\n\r\n            .table-card {\r" +
                    "\n                background-color: var(--card);\r\n                border: 1px sol" +
                    "id var(--border);\r\n                border-radius: var(--radius-xl);\r\n           " +
                    "     overflow: hidden;\r\n                box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1)" +
                    ";\r\n            }\r\n\r\n            .table-header {\r\n                padding: 24px;\r" +
                    "\n                border-bottom: 1px solid var(--border);\r\n            }\r\n\r\n     " +
                    "       .table-title {\r\n                font-size: 20px;\r\n                font-we" +
                    "ight: 700;\r\n                color: var(--foreground);\r\n            }\r\n\r\n        " +
                    "    .table-responsive {\r\n                overflow-x: auto;\r\n            }\r\n\r\n   " +
                    "         .gv-beneficiaries {\r\n                width: 100%;\r\n                bord" +
                    "er-collapse: collapse;\r\n            }\r\n\r\n            .gv-beneficiaries th {\r\n   " +
                    "             background-color: var(--secondary);\r\n                color: var(--f" +
                    "oreground);\r\n                font-weight: 600;\r\n                font-size: 13px;" +
                    "\r\n                text-align: left;\r\n                padding: 16px 24px;\r\n      " +
                    "          border: none;\r\n            }\r\n\r\n            .gv-beneficiaries td {\r\n  " +
                    "              padding: 16px 24px;\r\n                border-bottom: 1px solid var(" +
                    "--border);\r\n                font-size: 14px;\r\n            }\r\n\r\n            .gv-b" +
                    "eneficiaries tr:last-child td {\r\n                border-bottom: none;\r\n         " +
                    "   }\r\n\r\n            .gv-beneficiaries tr:hover {\r\n                background-col" +
                    "or: var(--secondary);\r\n            }\r\n\r\n            .btn-delete {\r\n             " +
                    "   background-color: var(--destructive);\r\n                color: var(--destructi" +
                    "ve-foreground);\r\n                border: none;\r\n                padding: 6px 12p" +
                    "x;\r\n                border-radius: var(--radius-sm);\r\n                font-size:" +
                    " 12px;\r\n                font-weight: 500;\r\n                cursor: pointer;\r\n   " +
                    "             transition: all 0.2s;\r\n            }\r\n\r\n            .btn-delete:hov" +
                    "er {\r\n                background-color: #dc2626;\r\n            }\r\n\r\n            ." +
                    "empty-state {\r\n                padding: 60px 20px;\r\n                text-align: " +
                    "center;\r\n                color: var(--muted-foreground);\r\n            }\r\n\r\n     " +
                    "       .btn-add {\r\n                background-color: var(--primary);\r\n          " +
                    "      color: var(--primary-foreground);\r\n                border: none;\r\n        " +
                    "        padding: 8px 16px;\r\n                border-radius: var(--radius-md);\r\n  " +
                    "              font-size: 13px;\r\n                font-weight: 500;\r\n             " +
                    "   cursor: pointer;\r\n                transition: all 0.2s;\r\n                text" +
                    "-decoration: none;\r\n                display: flex;\r\n                align-items:" +
                    " center;\r\n                gap: 6px;\r\n            }\r\n\r\n            .btn-add:hover" +
                    " {\r\n                background-color: #4338ca;\r\n            }\r\n\r\n            .ba" +
                    "ck-btn {\r\n                background-color: var(--secondary);\r\n                c" +
                    "olor: var(--foreground);\r\n                border: none;\r\n                padding" +
                    ": 8px 16px;\r\n                border-radius: var(--radius-md);\r\n                f" +
                    "ont-size: 13px;\r\n                font-weight: 500;\r\n                cursor: poin" +
                    "ter;\r\n                transition: all 0.2s;\r\n                text-decoration: no" +
                    "ne;\r\n                display: flex;\r\n                align-items: center;\r\n     " +
                    "           gap: 6px;\r\n            }\r\n\r\n            .back-btn:hover {\r\n          " +
                    "      background-color: var(--muted);\r\n            }\r\n\r\n            @media (max-" +
                    "width: 768px) {\r\n\r\n                .gv-beneficiaries th,\r\n                .gv-be" +
                    "neficiaries td {\r\n                    padding: 12px 16px;\r\n                    f" +
                    "ont-size: 13px;\r\n                }\r\n            }\r\n        </style>\r\n\r\n        <" +
                    "script>\r\n            function confirmDelete() {\r\n                return confirm(" +
                    "\'Are you sure you want to delete this beneficiary?\');\r\n            }\r\n        </" +
                    "script>\r\n    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        454,
                        4014,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent2(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 8 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 8 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control4() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n        Manage Beneficiaries\r\n    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4565,
                        36,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent3(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 146 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 146 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control5() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4699,
                        10,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnAddNew() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.Button)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.Button))));
            }
            else {
                
                #line 151 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
                @__ctrl = new global::System.Web.UI.WebControls.Button();
                
                #line default
                #line hidden
            }
            this.btnAddNew = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 151 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.ID = "btnAddNew";
            
            #line default
            #line hidden
            
            #line 151 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.Text = "Add New";
            
            #line default
            #line hidden
            
            #line 151 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.CssClass = "btn-add";
            
            #line default
            #line hidden
            
            #line 151 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.Click -= new System.EventHandler(this.btnAddNew_Click);
            
            #line default
            #line hidden
            
            #line 151 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.Click += new System.EventHandler(this.btnAddNew_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4709,
                        104,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control6() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n        <a href=\"Dashboard.aspx\" class=\"back-btn\">\r\n            <iconify-icon i" +
                    "con=\"lucide:arrow-left\" style=\"font-size: 16px\"></iconify-icon>\r\n            Bac" +
                    "k to Dashboard\r\n        </a>\r\n    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4813,
                        195,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent4(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 150 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl1 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 150 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl2;
            
            #line 150 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl2 = this.@__BuildControlbtnAddNew();
            
            #line default
            #line hidden
            
            #line 150 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 150 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl3 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 150 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control7() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
        <div class=""page-container"">
            <div class=""table-card"">
                <div class=""table-header"">
                    <div class=""table-title"">Saved Beneficiaries</div>
                </div>

                <div class=""table-responsive"">
                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5107,
                        288,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control9() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                            <div class=""empty-state"">
                                <iconify-icon icon=""lucide:users""
                                    style=""font-size: 48px; opacity: 0.3; margin-bottom: 12px""></iconify-icon>
                                <div>No beneficiaries added yet</div>
                                <div style=""margin-top: 8px; font-size: 13px;"">Click ""Add New"" to add your first
                                    beneficiary</div>
                            </div>
                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6547,
                        536,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control8(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 166 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl1 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 166 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control11() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 170 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 170 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.DataField = "Nickname";
            
            #line default
            #line hidden
            
            #line 170 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.HeaderText = "Nickname";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control12() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 171 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 171 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.DataField = "FullName";
            
            #line default
            #line hidden
            
            #line 171 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.HeaderText = "Full Name";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control13() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 172 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 172 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.DataField = "Email";
            
            #line default
            #line hidden
            
            #line 172 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.HeaderText = "Email";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control16() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6048,
                        38,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControl__control17() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.Button)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.Button))));
            }
            else {
                
                #line 175 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
                @__ctrl = new global::System.Web.UI.WebControls.Button();
                
                #line default
                #line hidden
            }
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 175 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.ID = "btnDelete";
            
            #line default
            #line hidden
            
            #line 175 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.Text = "Delete";
            
            #line default
            #line hidden
            
            #line 175 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.CssClass = "btn-delete";
            
            #line default
            #line hidden
            
            #line 175 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.CommandName = "DeleteBeneficiary";
            
            #line default
            #line hidden
            
            #line 175 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.OnClientClick = "return confirmDelete();";
            
            #line default
            #line hidden
            
            #line 175 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control17);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6086,
                        281,
                        false});
            return @__ctrl;
        }
        
        public void @__DataBinding__control17(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.Button dataBindingExpressionBuilderTarget;
            System.Web.UI.IDataItemContainer Container;
            
            #line 175 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Button)(sender));
            
            #line default
            #line hidden
            
            #line 175 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));
            
            #line default
            #line hidden
            
            #line 175 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            dataBindingExpressionBuilderTarget.CommandArgument = global::System.Convert.ToString( Eval("BeneficiaryID") , global::System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control18() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6367,
                        34,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control15(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 173 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl1 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 173 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl2;
            
            #line 173 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl2 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            
            #line 173 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 173 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl3 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            
            #line 173 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TemplateField @__BuildControl__control14() {
            global::System.Web.UI.WebControls.TemplateField @__ctrl;
            
            #line 173 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TemplateField();
            
            #line default
            #line hidden
            
            #line 173 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control15), null);
            
            #line default
            #line hidden
            
            #line 173 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.HeaderText = "Action";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control10(System.Web.UI.WebControls.DataControlFieldCollection @__ctrl) {
            global::System.Web.UI.WebControls.BoundField @__ctrl1;
            
            #line 166 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl1 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 166 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl2;
            
            #line 166 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl2 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 166 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl3;
            
            #line 166 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl3 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 166 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TemplateField @__ctrl4;
            
            #line 166 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl4 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 166 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgvBeneficiaries() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            System.IServiceProvider @__activator;
            @__activator = System.Web.HttpRuntime.WebObjectActivator;
            if ((@__activator != null)) {
                @__ctrl = ((System.Web.UI.WebControls.GridView)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(System.Web.UI.WebControls.GridView))));
            }
            else {
                
                #line 166 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
                @__ctrl = new global::System.Web.UI.WebControls.GridView();
                
                #line default
                #line hidden
            }
            this.gvBeneficiaries = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 166 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.EmptyDataTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control8));
            
            #line default
            #line hidden
            
            #line 166 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.ID = "gvBeneficiaries";
            
            #line default
            #line hidden
            
            #line 166 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.AutoGenerateColumns = false;
            
            #line default
            #line hidden
            
            #line 166 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.CssClass = "gv-beneficiaries";
            
            #line default
            #line hidden
            
            #line 166 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.None;
            
            #line default
            #line hidden
            
            #line 166 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.ShowHeader = true;
            
            #line default
            #line hidden
            
            #line 166 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            this.@__BuildControl__control10(@__ctrl.Columns);
            
            #line default
            #line hidden
            
            #line 166 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.RowCommand -= new System.Web.UI.WebControls.GridViewCommandEventHandler(this.gvBeneficiaries_RowCommand);
            
            #line default
            #line hidden
            
            #line 166 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.RowCommand += new System.Web.UI.WebControls.GridViewCommandEventHandler(this.gvBeneficiaries_RowCommand);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5395,
                        1745,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control19() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </div>\r\n            </div>\r\n        </div>\r\n    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        7140,
                        66,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent5(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 158 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl1 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 158 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.GridView @__ctrl2;
            
            #line 158 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl2 = this.@__BuildControlgvBeneficiaries();
            
            #line default
            #line hidden
            
            #line 158 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 158 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl3 = this.@__BuildControl__control19();
            
            #line default
            #line hidden
            
            #line 158 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(managebeneficiaries_aspx @__ctrl) {
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.Title = "Manage Beneficiaries";
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__ctrl.MasterPageFile = "~/Main.Master";
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 4 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            this.AddContentTemplate("TitleContent", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            
            #line 8 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            this.AddContentTemplate("HeadContent", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent2)));
            
            #line default
            #line hidden
            
            #line 146 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            this.AddContentTemplate("PageTitle", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent3)));
            
            #line default
            #line hidden
            
            #line 150 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            this.AddContentTemplate("TopActions", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent4)));
            
            #line default
            #line hidden
            
            #line 158 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            this.AddContentTemplate("MainContent", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent5)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n    "));
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n    "));
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n    "));
            
            #line default
            #line hidden
            
            #line 1 "D:\Project\OnlineBankingTransactionSystem\ManageBeneficiaries.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n    "));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.managebeneficiaries_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.managebeneficiaries_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -420935896;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
